/**
 * A-3 合并后的兼容转发层（second-impl-audit.md A-3）。
 *
 * 唯一实现在 `../omp/tools/auto-generated-guard.ts`（OMP 逐字移植 + T17-1
 * Windows basename 修复）。原「简化重写」已删除：SimpleLRU、手搓 peekFile、
 * 截断的三步整改文案、推送开关全部移除；开关语义改为 settings-pull
 * （`edit.blockAutoGenerated`，三级回退 activeSettings → 全局 settings →
 * schema 默认 true，refs settings-schema.ts:3230）。
 */
export {
	assertEditableFile,
	assertEditableFileContent,
} from '../omp/tools/auto-generated-guard.ts'

/**
 * @deprecated 兼容旧推送式 API：守卫已改为 settings-pull（调用方传
 * session.settings，未传时回退全局/默认），推送开关不再参与行为判定。
 * 保留为 no-op 以兼容既有 import；src/index.ts 的调用点已删除。
 */
export function setBlockAutoGenerated(_enabled: boolean): void {}