/**
 * DSH-adapted auto-generated guard (minimal, Node-only).
 * Port of OMP auto-generated-guard.ts without Bun/pi-utils.
 */
import * as path from 'node:path'
import * as fs from 'node:fs/promises'
import { ToolError } from './tool-errors.ts'

const CHECK_BYTE_COUNT = 1024
const HEADER_LINE_LIMIT = 40

const KNOWN_GENERATOR_PATTERN =
  '(?:protoc(?:-gen-[\\w-]+)?|sqlc|buf|swagger(?:-codegen)?|openapi(?:-generator)?|grpc-gateway|mockery|stringer|easyjson|deepcopy-gen|defaulter-gen|conversion-gen|client-gen|lister-gen|informer-gen|kysely-codegen|napi-rs)'

const AUTO_GENERATED_HEADER_MARKERS: readonly RegExp[] = [
  /@generated\b/i,
  /\bcode\s+generated\s+by\s+[a-z0-9_.-]+/i,
  /\bthis\s+file\s+was\s+automatically\s+generated\b/i,
  new RegExp(`\\bgenerated\\s+by\\s+${KNOWN_GENERATOR_PATTERN}\\b`, 'i'),
]

type CommentStyle = 'slash' | 'hash' | 'sql' | 'html'

const COMMENT_STYLES_BY_EXTENSION = new Map<string, readonly CommentStyle[]>([
  ['.c', ['slash']], ['.cc', ['slash']], ['.cpp', ['slash']], ['.cs', ['slash']], ['.dart', ['slash']], ['.go', ['slash']],
  ['.h', ['slash']], ['.hpp', ['slash']], ['.java', ['slash']], ['.js', ['slash']], ['.jsx', ['slash']], ['.kt', ['slash']], ['.kts', ['slash']],
  ['.mjs', ['slash']], ['.cjs', ['slash']], ['.php', ['slash']], ['.rs', ['slash']], ['.scala', ['slash']], ['.swift', ['slash']], ['.ts', ['slash']], ['.tsx', ['slash']],
  ['.py', ['hash']], ['.rb', ['hash']], ['.sh', ['hash']], ['.bash', ['hash']], ['.zsh', ['hash']], ['.yml', ['hash']], ['.yaml', ['hash']], ['.toml', ['hash']], ['.ini', ['hash']], ['.cfg', ['hash']], ['.conf', ['hash']], ['.env', ['hash']], ['.pl', ['hash']], ['.r', ['hash']],
  ['.sql', ['sql']], ['.html', ['html']], ['.htm', ['html']], ['.xml', ['html']], ['.svg', ['html']], ['.xhtml', ['html']],
])

const COMMENT_STYLES_BY_BASENAME = new Map<string, readonly CommentStyle[]>([
  ['dockerfile', ['hash']], ['makefile', ['hash']], ['justfile', ['hash']],
])

const AUTO_GENERATED_FILENAME_PATTERNS = [
  /^zz_generated\./,
  /\.pb\.(go|cc|h|c|js|ts)$/,
  /_pb2\.py$/,
  /_pb2_grpc\.py$/,
  /\.gen\.(go|ts|js|py)$/,
  /^generated\.(go|ts|js|py)$/,
  /\.swagger\.json$/,
  /\.openapi\.json$/,
  /\.mock\.(go|ts)$/,
  /\.mocks?\.(go|ts|js)$/,
]

function stripBom(content: string): string {
  if (content.charCodeAt(0) === 0xfeff) return content.slice(1)
  return content
}

function getCommentStylesForPath(filePath: string): readonly CommentStyle[] {
  const normalizedPath = filePath.toLowerCase()
  const fileName = path.basename(normalizedPath)
  const stylesByName = COMMENT_STYLES_BY_BASENAME.get(fileName)
  if (stylesByName) return stylesByName
  const ext = path.extname(fileName)
  return COMMENT_STYLES_BY_EXTENSION.get(ext) ?? []
}

function extractLeadingHeaderCommentText(content: string, commentStyles: readonly CommentStyle[]): string {
  if (commentStyles.length === 0) return ''
  const includeSlash = commentStyles.includes('slash')
  const includeHash = commentStyles.includes('hash')
  const includeSql = commentStyles.includes('sql')
  const includeHtml = commentStyles.includes('html')
  const lines = stripBom(content).split(/\r?\n/)
  const headerLines: string[] = []
  let started = false
  let inSlashBlock = false
  let inHtmlBlock = false
  for (let lineIndex = 0; lineIndex < lines.length && lineIndex < HEADER_LINE_LIMIT; lineIndex++) {
    const trimmed = lines[lineIndex]?.trim() ?? ''
    if (lineIndex === 0 && trimmed.startsWith('#!')) continue
    if (inSlashBlock) { headerLines.push(trimmed); if (trimmed.includes('*/')) inSlashBlock = false; continue }
    if (inHtmlBlock) { headerLines.push(trimmed); if (trimmed.includes('-->')) inHtmlBlock = false; continue }
    if (trimmed.length === 0) { if (started) headerLines.push(''); continue }
    if (includeSlash && trimmed.startsWith('//')) { started = true; headerLines.push(trimmed); continue }
    if (includeSlash && trimmed.startsWith('/*')) { started = true; headerLines.push(trimmed); if (!trimmed.includes('*/')) inSlashBlock = true; continue }
    if (includeHash && trimmed.startsWith('#')) { started = true; headerLines.push(trimmed); continue }
    if (includeSql && trimmed.startsWith('--')) { started = true; headerLines.push(trimmed); continue }
    if (includeHtml && trimmed.startsWith('<!--')) { started = true; headerLines.push(trimmed); if (!trimmed.includes('-->')) inHtmlBlock = true; continue }
    if (started) break
    break
  }
  return headerLines.join('\n')
}

function isAutoGeneratedFileName(filePath: string): boolean {
  const fileName = filePath.split('/').pop() ?? ''
  return AUTO_GENERATED_FILENAME_PATTERNS.some(p => p.test(fileName))
}

function detectAutoGeneratedMarker(content: string, filePath: string): string | undefined {
  const commentStyles = getCommentStylesForPath(filePath)
  const headerCommentText = extractLeadingHeaderCommentText(content, commentStyles)
  if (!headerCommentText) return undefined
  for (const markerPattern of AUTO_GENERATED_HEADER_MARKERS) {
    const match = markerPattern.exec(headerCommentText)
    if (match?.[0]) return match[0]
  }
  return undefined
}

function buildAutoGeneratedError(displayPath: string, detected: string): ToolError {
  return new ToolError(
    `Cannot modify auto-generated file: ${displayPath}\n\nThis file appears to be automatically generated (detected marker: "${detected}").\nAuto-generated files should not be edited directly.`,
  )
}

// Simple LRU cache shim (Map with max entries, no size tracking)
class SimpleLRU<K, V> {
  private map = new Map<K, V>()
  constructor(private max: number) {}
  get(key: K): V | undefined {
    const v = this.map.get(key)
    if (v !== undefined) { this.map.delete(key); this.map.set(key, v) }
    return v
  }
  set(key: K, value: V): void {
    if (this.map.has(key)) this.map.delete(key)
    this.map.set(key, value)
    if (this.map.size > this.max) {
      const first = this.map.keys().next().value as K
      this.map.delete(first)
    }
  }
}

const autoGeneratedMap = new SimpleLRU<string, { mtimeMs: number; size: number; marker: string | undefined }>(10)

async function getAutoGeneratedMarker(filePath: string): Promise<string | undefined> {
  if (isAutoGeneratedFileName(filePath)) return filePath.split('/').pop() ?? ''
  let mtimeMs: number, size: number
  try {
    const stat = await fs.stat(filePath)
    mtimeMs = stat.mtimeMs
    size = stat.size
  } catch (err: any) {
    if (err?.code === 'ENOENT') return undefined
    throw err
  }
  const cached = autoGeneratedMap.get(filePath)
  if (cached && cached.mtimeMs === mtimeMs && cached.size === size) return cached.marker
  let marker: string | undefined
  try {
    const handle = await fs.open(filePath, 'r')
    try {
      const buf = Buffer.alloc(CHECK_BYTE_COUNT)
      const { bytesRead } = await handle.read(buf, 0, CHECK_BYTE_COUNT, 0)
      const content = buf.subarray(0, bytesRead).toString('utf-8')
      marker = detectAutoGeneratedMarker(content, filePath)
    } finally { await handle.close() }
  } catch (err: any) {
    if (err?.code === 'ENOENT') return undefined
    throw err
  }
  autoGeneratedMap.set(filePath, { mtimeMs, size, marker })
  return marker
}

// OMP `edit.blockAutoGenerated` (default true). The plugin entry flips this
// from the resolved settings so the guard tracks the live config without a
// settings dependency inside this module.
let blockAutoGenerated = true

/** Update whether auto-generated files are blocked (`edit.blockAutoGenerated`). */
export function setBlockAutoGenerated(enabled: boolean): void {
  blockAutoGenerated = enabled
}

function shouldBlockAutoGeneratedFiles(): boolean {
  return blockAutoGenerated
}

export async function assertEditableFile(absolutePath: string, displayPath?: string): Promise<void> {
  if (!shouldBlockAutoGeneratedFiles()) return
  const pathForDisplay = displayPath ?? absolutePath
  const marker = await getAutoGeneratedMarker(absolutePath)
  if (marker) throw buildAutoGeneratedError(pathForDisplay, marker)
}

export function assertEditableFileContent(content: string, displayPath: string): void {
  if (!shouldBlockAutoGeneratedFiles()) return
  const prefix = content.slice(0, CHECK_BYTE_COUNT)
  const marker = detectAutoGeneratedMarker(prefix, displayPath)
  if (marker) throw buildAutoGeneratedError(displayPath, marker)
}
