/**
 * DSH adapter for the native (Rust) hashline engine.
 *
 * Upstream deleted the TypeScript `@oh-my-pi/hashline` package in 18.x and
 * rewrote the engine as `crates/pi-edit/src/modes/hashline/*.rs`, exposed
 * through `@oh-my-pi/pi-natives`. This module is the single seam DSH keeps
 * against it, and it is a **verbatim port** of the two upstream TS files that
 * replaced the old engine surface:
 *
 * - `refs/oh-my-pi/packages/coding-agent/src/tools/hashline-format.ts` (41L)
 *   → the `HL_*` constants plus the format/hash helpers below.
 * - `refs/oh-my-pi/packages/coding-agent/src/edit/store.ts` (19L)
 *   → {@link getEditStore}.
 *
 * The multi-mode transport (`Patcher`/`Filesystem`/`Clipboard`/`InMemorySnapshotStore`)
 * is gone on purpose: `EditSession.apply` owns staging, snapshot validation,
 * `N*` block resolution, clipboard registers, the no-op loop guard, and the
 * model-facing text. Hosts only supply an {@link EditPolicy} and a writer
 * callback — see `./policy.ts` and `./writer.ts`.
 *
 * `tsconfig.json` aliases `@oh-my-pi/hashline` onto this module, so the DSH
 * tools that only need the display/format helpers (read / write / grep /
 * ast-edit / ast-grep / plan-mode-guard) import it directly.
 */
import {
	blockRangeAt,
	EditSession,
	EditStore,
	editAutoGeneratedMessage,
	editDescription,
	editDiffString,
	editGrammar,
	editInspect,
	hashlineCountOps,
	hashlineFileHash,
	hashlineFormatHeader,
	hashlineFormatNumberedLines,
	hashlineStripPrefixes,
	structuredPatchHunks,
} from "@oh-my-pi/pi-natives";
import type {
	BlockRange,
	BlockRangeOptions,
	EditApplyOutcome,
	EditApplyRequest,
	EditDiffResult,
	EditFileOpIntent,
	EditFileOutcome,
	EditFilePreview,
	EditInspection,
	EditMatcherEntry,
	EditPolicy,
	EditPreviewBatch,
	EditVaultRoot,
	EditWriteRequest,
	EditWriteResponse,
} from "@oh-my-pi/pi-natives";
import { buildCompactDiffPreview } from "./diff-preview.ts";
import type { CompactDiffOptions, CompactDiffPreview } from "./diff-preview.ts";
import { detectLineEnding, normalizeToLF, restoreLineEndings, stripBom } from "./normalize.ts";
import type { BomResult, LineEnding } from "./normalize.ts";

/* -------------------------------------------------------------------------- */
/* Display format constants (upstream tools/hashline-format.ts:8-14)           */
/* -------------------------------------------------------------------------- */

/** Opens the `[path#tag]` section header. */
export const HL_FILE_PREFIX = "[";
/** Closes the `[path#tag]` section header. */
export const HL_FILE_SUFFIX = "]";
/** Separates the path from the tag inside a section header. */
export const HL_FILE_HASH_SEP = "#";
/** Hex digits in a section tag. */
export const HL_FILE_HASH_LENGTH = 4;
/** `MV` op keyword. */
export const HL_MOVE_KEYWORD = "MV";
/** `REM` op keyword. */
export const HL_REM_KEYWORD = "REM";
/** Separates an op locator from its body. */
export const HL_LINE_BODY_SEP = ":";

/* -------------------------------------------------------------------------- */
/* Format / hash helpers (verbatim upstream shims onto the native engine)      */
/* -------------------------------------------------------------------------- */

/** `[path#TAG]` section header. */
export function formatHashlineHeader(path: string, tag: string): string {
	return hashlineFormatHeader(path, tag);
}

/** `N:line` numbered display rows starting at `startLine` (default 1). */
export function formatNumberedLines(text: string, startLine?: number): string {
	return hashlineFormatNumberedLines(text, startLine);
}

/**
 * One `N:line` display row. Composed in TS rather than delegated: the native
 * surface has no single-line formatter (`hashlineFormatNumberedLines` takes a
 * whole text), and the JS join is byte-identical to the native row shape —
 * upstream composes it the same way (hashline-format.ts:26-28).
 */
export function formatNumberedLine(lineNumber: number, line: string): string {
	return `${lineNumber}:${line}`;
}

/**
 * Split `text` into addressable rows, dropping the empty row a trailing
 * newline produces. Upstream hashline-format.ts:30-34; the native engine
 * numbers the same way internally.
 */
export function splitAddressableFileLines(text: string): string[] {
	const lines = text.split("\n");
	if (lines.at(-1) === "") lines.pop();
	return lines;
}

/** Strip hashline display prefixes (`N:` / `+N:` …) from pasted rows. */
export function stripHashlinePrefixes(lines: string[]): string[] {
	return hashlineStripPrefixes(lines);
}

/** 4-hex hashline content tag for `text`. */
export function computeFileHash(text: string): string {
	return hashlineFileHash(text);
}

/* -------------------------------------------------------------------------- */
/* Session store (verbatim upstream edit/store.ts)                             */
/* -------------------------------------------------------------------------- */

/** Owner of the lazily created per-session store. */
export interface EditStoreOwner {
	editStore?: EditStore;
}

/**
 * The session's store, created on first use (verbatim upstream
 * `edit/store.ts:15-18`).
 *
 * One store per session carries the full-file snapshots that mint hashline
 * tags, the `CUT`/`PUT` clipboard registers, and the byte-identical no-op loop
 * guard — every {@link EditSession} the edit tool opens shares it, and the
 * read/search/write tools mint their tags into it.
 *
 * DSH note: DSH rebuilds its `ToolSession` object on every tool call and
 * round-trips the store through `shared/session-state.ts`, so the engine path
 * reaches the store through `getFileSnapshotStore` in
 * `src/tools/omp/edit/file-snapshot-store.ts`, which delegates here.
 */
export function getEditStore(session: EditStoreOwner): EditStore {
	session.editStore ??= new EditStore();
	return session.editStore;
}

/* -------------------------------------------------------------------------- */
/* DSH error type for native rejections                                        */
/* -------------------------------------------------------------------------- */

/**
 * Raised when the native engine rejects a payload.
 *
 * The Rust engine reports every rejection as an `isError` outcome carrying the
 * model-facing text — mismatched tag, unseen anchor line, missing file, no-op
 * escalation (upstream `edit/index.ts:495-497` returns it as a tool result).
 * DSH's `edit` tool contract is throw-based (`toText` in
 * `src/tools/edit/adapter/index.ts` throws when a result is `isError`), and
 * DSH's per-file detail shape carries `displayErrorText` sourced from
 * `MismatchError.displayMessage` (`details.ts`, `dispatch.ts`), so
 * `executeHashlineSingle` re-raises the native text as this class. Both
 * `message` and `displayMessage` are exactly the native text, so the model
 * sees the teaching message unchanged.
 *
 * (Upstream's pre-18.0 `MismatchError` formatted its own richer diagnostic
 * from structured fields; the native text already contains that diagnostic,
 * hence the single-string shape.)
 */
export class MismatchError extends Error {
	/** Model/TUI-facing text — always identical to {@link Error.message}. */
	readonly displayMessage: string;

	constructor(message: string) {
		super(message);
		this.name = "MismatchError";
		this.displayMessage = message;
	}
}

/* -------------------------------------------------------------------------- */
/* Thin re-exports of the native transport                                     */
/* -------------------------------------------------------------------------- */

/*
 * `blockRangeAt` is a native *primitive*, not part of the hashline-format
 * surface: the `N*` block locator is resolved inside the Rust engine, and DSH
 * no longer needs a `BlockResolver` (the vendored `block-resolver.ts` that
 * wrapped this call was deleted with the TS engine). It stays re-exported so
 * structured assertions on a block's line span can reach the same primitive
 * the engine uses instead of re-deriving it from rendered text.
 *
 * `buildCompactDiffPreview` and the line-ending/BOM helpers (`detectLineEnding`,
 * `normalizeToLF`, `restoreLineEndings`, `stripBom` and their types) are
 * likewise absent from the native surface but still consumed through this
 * alias — by `omp/edit/normalize.ts` (which re-exports them) and by the
 * diff/apply-patch engines. They are verbatim ports of the deleted
 * `engine/diff-preview.ts` and `engine/normalize.ts`; see those files for the
 * provenance notes.
 */

export {
	blockRangeAt,
	buildCompactDiffPreview,
	detectLineEnding,
	EditStore,
	EditSession,
	editAutoGeneratedMessage,
	editDescription,
	editDiffString,
	editGrammar,
	editInspect,
	hashlineCountOps,
	normalizeToLF,
	restoreLineEndings,
	stripBom,
	structuredPatchHunks,
};

export type {
	BlockRange,
	BlockRangeOptions,
	BomResult,
	CompactDiffOptions,
	CompactDiffPreview,
	EditApplyOutcome,
	EditApplyRequest,
	EditDiffResult,
	EditFileOpIntent,
	EditFileOutcome,
	EditFilePreview,
	EditInspection,
	EditMatcherEntry,
	EditPolicy,
	EditPreviewBatch,
	EditVaultRoot,
	EditWriteRequest,
	EditWriteResponse,
	LineEnding,
};
