/**
 * tool-plus 统一 OMP 配置注册表（单一事实源）。
 *
 * 所有移植工具（read/write/edit/grep/glob/ast_edit/ast_grep）的 OMP settings
 * 键集中定义在这里：
 * - `OMP_DEFAULTS`：每个键的默认值，verbatim 取自 OMP `config/settings-schema.ts`
 *   （refs/oh-my-pi/packages/coding-agent/src/config/settings-schema.ts，5880 行注册表），
 *   引擎行为与上游一致。
 * - `OMP_KEY_TO_FIELD`：OMP dotted key → DSH tool-plus 扁平配置字段（fields.ts）
 *   的映射；未映射的键走默认值（如 LSP/web-search/autoqa 等 DSH 不暴露的
 *   能力，默认值兜底即可，不会降级）。
 *
 * 各工具 adapter 的 `config/settings.ts` / `config/settings-schema.ts` 引用
 * 本模块，消除多份重复定义。新增配置键只改这里 + fields.ts。
 */

/** OMP dotted key -> flat tool-plus config field (when present). */
export const OMP_KEY_TO_FIELD: Record<string, string | undefined> = {
  // edit.*
  'edit.mode': 'editMode',
  'edit.blockAutoGenerated': 'editBlockAutoGenerated',
  'edit.fuzzyMatch': 'editFuzzyMatch',
  'edit.fuzzyThreshold': 'editFuzzyThreshold',
  'edit.enforceSeenLines': 'editEnforceSeenLines',
  // read.*
  'read.defaultLimit': 'readDefaultLimit',
  'read.renderMarkdown': 'readRenderMarkdown',
  'read.summarize.enabled': 'readSummarizeEnabled',
  'read.summarize.prose': 'readSummarizeProse',
  'read.summarize.minBodyLines': 'readSummarizeMinBodyLines',
  'read.summarize.minCommentLines': 'readSummarizeMinCommentLines',
  'read.summarize.minTotalLines': 'readSummarizeMinTotalLines',
  'read.summarize.unfoldUntil': 'readSummarizeUnfoldUntil',
  'read.summarize.unfoldLimit': 'readSummarizeUnfoldLimit',
  // grep.*
  'grep.contextBefore': 'grepContextBefore',
  'grep.contextAfter': 'grepContextAfter',
  // 工具启用开关（ast_grep/ast_edit；glob/grep 不设开关，默认开启）
  'astGrep.enabled': 'astGrepEnabled',
  'astEdit.enabled': 'astEditEnabled',
  // fetch.* / tools.* / images.* / inspect_image.*（read/write 抓取与读图路径）
  'fetch.enabled': 'fetchEnabled',
  'tools.maxTimeout': 'fetchMaxTimeoutSeconds',
  'images.autoResize': 'imagesAutoResize',
  'inspect_image.mode': 'inspectImageMode',
  // 顶层键（非 dotted）
  readLineNumbers: 'readLineNumbers',
}

/**
 * OMP schema 默认值（verbatim，来源见上）。键 = OMP settings-schema.ts 的注册键。
 */
export const OMP_DEFAULTS: Record<string, unknown> = {
  // edit.*（settings-schema.ts 3200-3250 区间）
  // 注意：edit.mode 的 verbatim 默认是 hashline，但 DSH 配置字段（editMode）默认
  // 是 replace（用户拍板：Replace 更通用，与 OMP 有出入——见 plan.md 拍板#15）。
  // 引擎读 settings.get("edit.mode") 时经 OMP_KEY_TO_FIELD 命中 DSH 字段值（replace），
  // 此处的 hashline 仅作为无映射时的兜底。
  'edit.mode': 'hashline',
  'edit.blockAutoGenerated': true,
  'edit.fuzzyMatch': true,
  'edit.fuzzyThreshold': 0.95,
  'edit.enforceSeenLines': false,
  // read.*
  readLineNumbers: false,
  'read.defaultLimit': 300,
  'read.renderMarkdown': false,
  'read.summarize.enabled': true,
  'read.summarize.prose': false,
  'read.summarize.minBodyLines': 4,
  'read.summarize.minCommentLines': 6,
  'read.summarize.minTotalLines': 100,
  'read.summarize.unfoldUntil': 50,
  'read.summarize.unfoldLimit': 100,
  // grep.*
  'grep.contextBefore': 1,
  'grep.contextAfter': 3,
  // task.*（DSH 无子代理 spawn 场景，空列表兜底）
  'task.disabledAgents': [],
  // fetch.*
  'fetch.enabled': true,
  // tools.*（read 输出行宽兜底）
  'tools.maxTimeout': 0,
  'tools.outputMaxColumns': 768,
  // 工具启用开关默认值兜底
  'glob.enabled': true,
  'grep.enabled': true,
  // astGrep.enabled 默认 false（OMP 原版 settings-schema.ts:3831：ast_grep 默认禁用，
  // 需用户在设置面板开启）；astEdit.enabled 默认 true（settings-schema.ts:3842）。
  'astGrep.enabled': false,
  'astEdit.enabled': true,
  // images.*
  'images.autoResize': true,
  // inspect_image.*
  'inspect_image.mode': 'auto',
  // memory.*（DSH 虚拟路由去掉，恒 off）
  'memory.backend': 'off',
  // providers.*（web 抓取偏好；DSH 默认 auto）
  'providers.fetch': 'auto',
  'providers.webSearchTimeoutSeconds': 60,
  // exa.*
  'exa.enabled': true,
  'exa.searchDelayMs': 1_000,
  // searxng.*（endpoint 未配置 → undefined）
  'searxng.endpoint': undefined,
  // dev.*（report-tool-issue 兜底）
  'dev.autoqa': true,
  'dev.autoqaConsent': undefined,
}
