/**
 * Plugin-owned settings surface for the ported bash tool: the `bash-plus`
 * namespace, a FLAT settings schema (OMP `bash*`-style scalar keys — the
 * client scope writes scalar fields only), its defaults, the mapping onto the
 * nested {@link RuntimeConfig} the runtime consumes, and the optional-settings
 * consumer wiring. Keeping the whole config-export surface here lets the
 * ported OMP runtime stay pristine — the entry only calls
 * {@link installBashPlusSettings} and re-exports this module's `Config`.
 * @module @xiaoso/dsh-tool-plus/settings
 */

import type { Context } from '@deepseek-ai/cordis'
import z from '@deepseek-ai/schemastery'
import { installSettingsSection, settingsNamespace } from '@deepseek-ai/dsh-settings'
import type { MinimizerConfig } from '../tools/bash/types.ts'
import { TOOL_PLUS_FIELDS, toolPlusField, type ToolPlusFieldValue } from './fields.ts'

/** Truncation strategy for background→foreground completion messages (OMP config parity). */
export type OutputTruncateStrategy = 'bytes' | 'lines'

/** Retention mode for a truncated completion message: head, tail, or middle (head+tail). */
export type OutputRetentionMode = 'head' | 'tail' | 'middle'

/** Byte-based retention settings; `middle` keeps head+tail, `head`/`tail` keep one window. */
export interface ByteRetentionConfig {
  mode: OutputRetentionMode
  headBytes: number
  tailBytes: number
}

/** Reader-backend preference for URL reads (`providers.fetch` parity). */
export type FetchReaderPreference =
  | 'auto' | 'native' | 'trafilatura' | 'lynx' | 'parallel' | 'jina' | 'browser'

/** Line-based retention settings, mirroring the byte-based structure. */
export interface LineRetentionConfig {
  mode: OutputRetentionMode
  headLines: number
  tailLines: number
}

/**
 * Background-job completion text truncation (mirrors the OMP `bashOutputTruncate*`
 * family). Only the settled preview text is affected; streaming reads and the
 * completion notice are untouched.
 */
export interface OutputTruncateConfig {
  strategy: OutputTruncateStrategy
  /** Threshold (in `strategy` units) below which the text is kept intact. */
  triggerBytes: number
  triggerLines: number
  bytes: ByteRetentionConfig
  lines: LineRetentionConfig
}

/**
 * The resolved runtime configuration, nested for the OMP runtime consumers.
 * {@link RuntimeConfig} is built from the flat {@link Config} by
 * {@link resolveConfig}; the OMP-ported runtime files never see the flat shape.
 */
export interface RuntimeConfig {
  enableRunInBackground: boolean
  autoBackgroundMs: number
  defaultTimeoutMs: number
  maxTimeoutMs: number
  outputMaxBytes: number
  outputSinkTailBytes: number
  outputSinkHeadBytes: number
  minimizer: MinimizerConfig
  interceptorEnabled: boolean
  nonInteractiveEnv: boolean
  snapshotEnabled: boolean
  rmSafe: boolean
  useShellCommandWrapper: boolean
  maxBackgroundJobs: number
  outputTruncate: OutputTruncateConfig
  // File tools (OMP parity)
  editBlockAutoGenerated: boolean
  editMode: string
  editFuzzyMatch: boolean
  editFuzzyThreshold: number
  editEnforceSeenLines: boolean
  readSummarizeEnabled: boolean
  readSummarizeProse: boolean
  readSummarizeMinBodyLines: number
  readSummarizeMinCommentLines: number
  readSummarizeMinTotalLines: number
  readSummarizeUnfoldUntil: number
  readSummarizeUnfoldLimit: number
  readDefaultLimit: number
  readLineNumbers: boolean
  readRenderMarkdown: boolean
  readConcurrentSafe: boolean
  grepContextBefore: number
  grepContextAfter: number
  grepCaseDefault: boolean
  grepGitignoreDefault: boolean
  globGitignoreDefault: boolean
  globHiddenDefault: boolean
  astGrepEnabled: boolean
  astEditEnabled: boolean
  fetchEnabled: boolean
  fetchMaxTimeoutSeconds: number
  fetchReader: FetchReaderPreference
  browserReaderEnabled: boolean
  imagesAutoResize: boolean
  imagesBlockImages: boolean
  imagesExcludeWebp: boolean
  imagesInputMaxBytes: number
  imagesResizeMaxSide: number
  imagesResizeMaxBytes: number
  imagesResizeMinSide: number
  imagesResizeJpegQuality: number
}

/** Settings namespace of this plugin, served to the web Plugins page. */
export const BASH_PLUS_SETTINGS_NS = settingsNamespace('tool-plus')

/** OMP-parity defaults for the completion-message truncation policy. */
export const DEFAULT_OUTPUT_TRUNCATE: OutputTruncateConfig = {
  strategy: 'bytes',
  triggerBytes: 10_240,
  triggerLines: 100,
  bytes: { mode: 'middle', headBytes: 4_096, tailBytes: 4_096 },
  lines: { mode: 'middle', headLines: 50, tailLines: 100 },
}

/**
 * Timing knobs (ms). DEFAULT_MAX_TIMEOUT_MS is OMP-parity (= upstream bash
 * per-tool max 3600s); DEFAULT_TIMEOUT_MS was deliberately relaxed from
 * 300_000 to 3_600_000 with the bash-plus settings card (763023e,
 * 2026-08-19) — NOT OMP-parity (OMP bash default is 300s), compensated by
 * auto-backgrounding after DEFAULT_AUTO_BACKGROUND_MS. By design there is no
 * upstream `tools.maxTimeout` global-cap equivalent: maxTimeoutMs always
 * applies. (second-impl-audit.md S-11 终局, 2026-08-29.)
 */
export const DEFAULT_TIMEOUT_MS = 3_600_000
export const DEFAULT_MAX_TIMEOUT_MS = 3_600_000
export const DEFAULT_AUTO_BACKGROUND_MS = 60_000
export const DEFAULT_MAX_BACKGROUND_JOBS = 15

/**
 * Plugin settings, one scalar key per option — every field is writable through
 * the client `SettingsScope.set`/`unset`. Defaults live in the {@link Config}
 * schema and in {@link resolveConfig}.
 */
export interface Config {
  enableRunInBackground?: boolean
  autoBackgroundMs?: number
  defaultTimeoutMs?: number
  maxTimeoutMs?: number
  outputMaxBytes?: number
  outputSinkTailBytes?: number
  outputSinkHeadBytes?: number
  minimizerEnabled?: boolean
  interceptorEnabled?: boolean
  nonInteractiveEnv?: boolean
  snapshotEnabled?: boolean
  /** Redefine `rm` in the session shell to move into the system trash (default true). */
  rmSafe?: boolean
  useShellCommandWrapper?: boolean
  maxBackgroundJobs?: number
  outputTruncateStrategy?: OutputTruncateStrategy
  outputTruncateTriggerBytes?: number
  outputTruncateTriggerLines?: number
  outputTruncateByteMode?: OutputRetentionMode
  outputTruncateByteHeadBytes?: number
  outputTruncateByteTailBytes?: number
  outputTruncateLineMode?: OutputRetentionMode
  outputTruncateLineHeadLines?: number
  outputTruncateLineTailLines?: number
  // File tools (OMP `edit.blockAutoGenerated` / `read.summarize.*` parity)
  editBlockAutoGenerated?: boolean
  editMode?: 'replace' | 'patch' | 'hashline' | 'apply_patch'
  editFuzzyMatch?: boolean
  editFuzzyThreshold?: number
  editEnforceSeenLines?: boolean
  readSummarizeEnabled?: boolean
  readSummarizeProse?: boolean
  readSummarizeMinBodyLines?: number
  readSummarizeMinCommentLines?: number
  readSummarizeMinTotalLines?: number
  readSummarizeUnfoldUntil?: number
  readSummarizeUnfoldLimit?: number
  readDefaultLimit?: number
  readLineNumbers?: boolean
  readRenderMarkdown?: boolean
  readConcurrentSafe?: boolean
  grepContextBefore?: number
  grepContextAfter?: number
  grepCaseDefault?: boolean
  grepGitignoreDefault?: boolean
  globGitignoreDefault?: boolean
  globHiddenDefault?: boolean
  astGrepEnabled?: boolean
  astEditEnabled?: boolean
  fetchEnabled?: boolean
  fetchMaxTimeoutSeconds?: number
  fetchReader?: FetchReaderPreference
  browserReaderEnabled?: boolean
  imagesAutoResize?: boolean
  imagesBlockImages?: boolean
  imagesExcludeWebp?: boolean
  imagesInputMaxBytes?: number
  imagesResizeMaxSide?: number
  imagesResizeMaxBytes?: number
  imagesResizeMinSide?: number
  imagesResizeJpegQuality?: number
}

/** Schema default of one field, sourced from the single-source field table. */
function fieldDefault<T extends ToolPlusFieldValue>(name: string, fallback: T): T {
  const value = toolPlusField(name)?.default
  return (value === undefined ? fallback : value) as T
}

/**
 * Runtime configuration schema for the plugin. The namespace resolves through
 * this flat surface; {@link resolveConfig} maps it onto {@link RuntimeConfig}.
 */
export const Config: z<Config> = z.object({
  enableRunInBackground: z.boolean().default(fieldDefault('enableRunInBackground', true)),
  autoBackgroundMs: z.number().default(fieldDefault('autoBackgroundMs', DEFAULT_AUTO_BACKGROUND_MS)),
  defaultTimeoutMs: z.number().default(fieldDefault('defaultTimeoutMs', DEFAULT_TIMEOUT_MS)),
  maxTimeoutMs: z.number().default(fieldDefault('maxTimeoutMs', DEFAULT_MAX_TIMEOUT_MS)),
  outputMaxBytes: z.number().default(fieldDefault('outputMaxBytes', 51_200)),
  outputSinkTailBytes: z.number().default(fieldDefault('outputSinkTailBytes', 51_200)),
  outputSinkHeadBytes: z.number().default(fieldDefault('outputSinkHeadBytes', 20_480)),
  minimizerEnabled: z.boolean().default(fieldDefault('minimizerEnabled', true)),
  interceptorEnabled: z.boolean().default(fieldDefault('interceptorEnabled', true)),
  nonInteractiveEnv: z.boolean().default(fieldDefault('nonInteractiveEnv', true)),
  snapshotEnabled: z.boolean().default(fieldDefault('snapshotEnabled', true)),
  rmSafe: z.boolean().default(fieldDefault('rmSafe', true)),
  useShellCommandWrapper: z.boolean().default(fieldDefault('useShellCommandWrapper', false)),
  maxBackgroundJobs: z.number().default(fieldDefault('maxBackgroundJobs', DEFAULT_MAX_BACKGROUND_JOBS)),
  outputTruncateStrategy: z.union(['bytes', 'lines'] as const).default(fieldDefault('outputTruncateStrategy', 'bytes')),
  outputTruncateTriggerBytes: z.number().default(fieldDefault('outputTruncateTriggerBytes', 10_240)),
  outputTruncateTriggerLines: z.number().default(fieldDefault('outputTruncateTriggerLines', 100)),
  outputTruncateByteMode: z.union(['head', 'tail', 'middle'] as const).default(fieldDefault('outputTruncateByteMode', 'middle')),
  outputTruncateByteHeadBytes: z.number().default(fieldDefault('outputTruncateByteHeadBytes', 4_096)),
  outputTruncateByteTailBytes: z.number().default(fieldDefault('outputTruncateByteTailBytes', 4_096)),
  outputTruncateLineMode: z.union(['head', 'tail', 'middle'] as const).default(fieldDefault('outputTruncateLineMode', 'middle')),
  outputTruncateLineHeadLines: z.number().default(fieldDefault('outputTruncateLineHeadLines', 50)),
  outputTruncateLineTailLines: z.number().default(fieldDefault('outputTruncateLineTailLines', 100)),
  // File tools — OMP defaults (settings-schema.ts:3228/3290ff)
  editBlockAutoGenerated: z.boolean().default(fieldDefault('editBlockAutoGenerated', true)),
  readSummarizeEnabled: z.boolean().default(fieldDefault('readSummarizeEnabled', true)),
  readSummarizeProse: z.boolean().default(fieldDefault('readSummarizeProse', false)),
  readSummarizeMinBodyLines: z.number().default(fieldDefault('readSummarizeMinBodyLines', 4)),
  readSummarizeMinCommentLines: z.number().default(fieldDefault('readSummarizeMinCommentLines', 6)),
  readSummarizeMinTotalLines: z.number().default(fieldDefault('readSummarizeMinTotalLines', 100)),
  readSummarizeUnfoldUntil: z.number().default(fieldDefault('readSummarizeUnfoldUntil', 50)),
  readSummarizeUnfoldLimit: z.number().default(fieldDefault('readSummarizeUnfoldLimit', 100)),
  // File tools — OMP 其余键（edit.mode/fuzzy/grep.* 等）
  editMode: z.union(['replace', 'patch', 'hashline', 'apply_patch'] as const).default(fieldDefault('editMode', 'replace')),
  editFuzzyMatch: z.boolean().default(fieldDefault('editFuzzyMatch', true)),
  editFuzzyThreshold: z.number().default(fieldDefault('editFuzzyThreshold', 0.95)),
  editEnforceSeenLines: z.boolean().default(fieldDefault('editEnforceSeenLines', false)),
  readDefaultLimit: z.number().default(fieldDefault('readDefaultLimit', 300)),
  readLineNumbers: z.boolean().default(fieldDefault('readLineNumbers', false)),
  readRenderMarkdown: z.boolean().default(fieldDefault('readRenderMarkdown', false)),
  readConcurrentSafe: z.boolean().default(fieldDefault('readConcurrentSafe', true)),
  grepContextBefore: z.number().default(fieldDefault('grepContextBefore', 1)),
  grepContextAfter: z.number().default(fieldDefault('grepContextAfter', 3)),
  // 搜索默认值开关（grep/glob 未显式传参时的默认；默认=上游硬编码 true）
  grepCaseDefault: z.boolean().default(fieldDefault('grepCaseDefault', true)),
  grepGitignoreDefault: z.boolean().default(fieldDefault('grepGitignoreDefault', true)),
  globGitignoreDefault: z.boolean().default(fieldDefault('globGitignoreDefault', true)),
  globHiddenDefault: z.boolean().default(fieldDefault('globHiddenDefault', true)),
  // AST 工具启用开关（OMP settings-schema.ts:3831/3842；astGrep 默认 false）
  astGrepEnabled: z.boolean().default(fieldDefault('astGrepEnabled', false)),
  astEditEnabled: z.boolean().default(fieldDefault('astEditEnabled', true)),
  // File tools — fetch（URL 抓取）与图片（拍板#22：read 图片路径已还原并入）
  fetchEnabled: z.boolean().default(fieldDefault('fetchEnabled', true)),
  fetchMaxTimeoutSeconds: z.number().default(fieldDefault('fetchMaxTimeoutSeconds', 0)),
  fetchReader: z.union(['auto', 'native', 'trafilatura', 'lynx', 'parallel', 'jina', 'browser'] as const).default(fieldDefault('fetchReader', 'auto')),
  browserReaderEnabled: z.boolean().default(fieldDefault('browserReaderEnabled', true)),
  imagesAutoResize: z.boolean().default(fieldDefault('imagesAutoResize', true)),
  imagesBlockImages: z.boolean().default(fieldDefault('imagesBlockImages', false)),
  imagesExcludeWebp: z.boolean().default(fieldDefault('imagesExcludeWebp', false)),
  imagesInputMaxBytes: z.number().default(fieldDefault('imagesInputMaxBytes', 20 * 1024 * 1024)),
  imagesResizeMaxSide: z.number().default(fieldDefault('imagesResizeMaxSide', 1568)),
  imagesResizeMaxBytes: z.number().default(fieldDefault('imagesResizeMaxBytes', 500 * 1024)),
  imagesResizeMinSide: z.number().default(fieldDefault('imagesResizeMinSide', 200)),
  imagesResizeJpegQuality: z.number().default(fieldDefault('imagesResizeJpegQuality', 80)),
})

/**
 * Resolve the flat settings (composition entry or the settings document) to
 * the nested runtime config the ported OMP runtime consumes. A direct mount
 * (`ctx.plugin`) skips the Loader's schema parse, so the `?? default` pass
 * mirrors the schema; the settings namespace resolution rides the same path.
 * @param config - flat settings, possibly partial and not schema-parsed.
 * @returns the fully-defaulted nested runtime config.
 */
export function resolveConfig(config: Config): RuntimeConfig {
  const resolveMinimizer = (): MinimizerConfig => ({
    enabled: config.minimizerEnabled ?? fieldDefault('minimizerEnabled', true),
    only: [],
    except: [],
    maxCaptureBytes: 512 * 1024,
  })
  return {
    enableRunInBackground: config.enableRunInBackground ?? fieldDefault('enableRunInBackground', true),
    autoBackgroundMs: config.autoBackgroundMs ?? fieldDefault('autoBackgroundMs', DEFAULT_AUTO_BACKGROUND_MS),
    defaultTimeoutMs: config.defaultTimeoutMs ?? fieldDefault('defaultTimeoutMs', DEFAULT_TIMEOUT_MS),
    maxTimeoutMs: config.maxTimeoutMs ?? fieldDefault('maxTimeoutMs', DEFAULT_MAX_TIMEOUT_MS),
    outputMaxBytes: config.outputMaxBytes ?? fieldDefault('outputMaxBytes', 51_200),
    outputSinkTailBytes: config.outputSinkTailBytes ?? fieldDefault('outputSinkTailBytes', 51_200),
    outputSinkHeadBytes: config.outputSinkHeadBytes ?? fieldDefault('outputSinkHeadBytes', 20_480),
    minimizer: resolveMinimizer(),
    interceptorEnabled: config.interceptorEnabled ?? fieldDefault('interceptorEnabled', true),
    nonInteractiveEnv: config.nonInteractiveEnv ?? fieldDefault('nonInteractiveEnv', true),
    snapshotEnabled: config.snapshotEnabled ?? fieldDefault('snapshotEnabled', true),
    rmSafe: config.rmSafe ?? fieldDefault('rmSafe', true),
    useShellCommandWrapper: config.useShellCommandWrapper ?? fieldDefault('useShellCommandWrapper', false),
    maxBackgroundJobs: config.maxBackgroundJobs ?? fieldDefault('maxBackgroundJobs', DEFAULT_MAX_BACKGROUND_JOBS),
    outputTruncate: {
      strategy: config.outputTruncateStrategy ?? fieldDefault('outputTruncateStrategy', DEFAULT_OUTPUT_TRUNCATE.strategy),
      triggerBytes: config.outputTruncateTriggerBytes ?? fieldDefault('outputTruncateTriggerBytes', DEFAULT_OUTPUT_TRUNCATE.triggerBytes),
      triggerLines: config.outputTruncateTriggerLines ?? fieldDefault('outputTruncateTriggerLines', DEFAULT_OUTPUT_TRUNCATE.triggerLines),
      bytes: {
        mode: config.outputTruncateByteMode ?? fieldDefault('outputTruncateByteMode', DEFAULT_OUTPUT_TRUNCATE.bytes.mode),
        headBytes: config.outputTruncateByteHeadBytes ?? fieldDefault('outputTruncateByteHeadBytes', DEFAULT_OUTPUT_TRUNCATE.bytes.headBytes),
        tailBytes: config.outputTruncateByteTailBytes ?? fieldDefault('outputTruncateByteTailBytes', DEFAULT_OUTPUT_TRUNCATE.bytes.tailBytes),
      },
      lines: {
        mode: config.outputTruncateLineMode ?? fieldDefault('outputTruncateLineMode', DEFAULT_OUTPUT_TRUNCATE.lines.mode),
        headLines: config.outputTruncateLineHeadLines ?? fieldDefault('outputTruncateLineHeadLines', DEFAULT_OUTPUT_TRUNCATE.lines.headLines),
        tailLines: config.outputTruncateLineTailLines ?? fieldDefault('outputTruncateLineTailLines', DEFAULT_OUTPUT_TRUNCATE.lines.tailLines),
      },
    },
    editBlockAutoGenerated: config.editBlockAutoGenerated ?? fieldDefault('editBlockAutoGenerated', true),
    readSummarizeEnabled: config.readSummarizeEnabled ?? fieldDefault('readSummarizeEnabled', true),
    readSummarizeProse: config.readSummarizeProse ?? fieldDefault('readSummarizeProse', false),
    readSummarizeMinBodyLines: config.readSummarizeMinBodyLines ?? fieldDefault('readSummarizeMinBodyLines', 4),
    readSummarizeMinCommentLines: config.readSummarizeMinCommentLines ?? fieldDefault('readSummarizeMinCommentLines', 6),
    readSummarizeMinTotalLines: config.readSummarizeMinTotalLines ?? fieldDefault('readSummarizeMinTotalLines', 100),
    readSummarizeUnfoldUntil: config.readSummarizeUnfoldUntil ?? fieldDefault('readSummarizeUnfoldUntil', 50),
    readSummarizeUnfoldLimit: config.readSummarizeUnfoldLimit ?? fieldDefault('readSummarizeUnfoldLimit', 100),
    editMode: config.editMode ?? fieldDefault('editMode', 'replace'),
    editFuzzyMatch: config.editFuzzyMatch ?? fieldDefault('editFuzzyMatch', true),
    editFuzzyThreshold: config.editFuzzyThreshold ?? fieldDefault('editFuzzyThreshold', 0.95),
    editEnforceSeenLines: config.editEnforceSeenLines ?? fieldDefault('editEnforceSeenLines', false),
    readDefaultLimit: config.readDefaultLimit ?? fieldDefault('readDefaultLimit', 300),
    readLineNumbers: config.readLineNumbers ?? fieldDefault('readLineNumbers', false),
    readRenderMarkdown: config.readRenderMarkdown ?? fieldDefault('readRenderMarkdown', false),
    readConcurrentSafe: config.readConcurrentSafe ?? fieldDefault('readConcurrentSafe', true),
    grepContextBefore: config.grepContextBefore ?? fieldDefault('grepContextBefore', 1),
    grepContextAfter: config.grepContextAfter ?? fieldDefault('grepContextAfter', 3),
    grepCaseDefault: config.grepCaseDefault ?? fieldDefault('grepCaseDefault', true),
    grepGitignoreDefault: config.grepGitignoreDefault ?? fieldDefault('grepGitignoreDefault', true),
    globGitignoreDefault: config.globGitignoreDefault ?? fieldDefault('globGitignoreDefault', true),
    globHiddenDefault: config.globHiddenDefault ?? fieldDefault('globHiddenDefault', true),
    astGrepEnabled: config.astGrepEnabled ?? fieldDefault('astGrepEnabled', false),
    astEditEnabled: config.astEditEnabled ?? fieldDefault('astEditEnabled', true),
    fetchEnabled: config.fetchEnabled ?? fieldDefault('fetchEnabled', true),
    fetchMaxTimeoutSeconds: config.fetchMaxTimeoutSeconds ?? fieldDefault('fetchMaxTimeoutSeconds', 0),
    fetchReader: config.fetchReader ?? fieldDefault('fetchReader', 'auto'),
    browserReaderEnabled: config.browserReaderEnabled ?? fieldDefault('browserReaderEnabled', true),
    imagesAutoResize: config.imagesAutoResize ?? fieldDefault('imagesAutoResize', true),
    imagesBlockImages: config.imagesBlockImages ?? fieldDefault('imagesBlockImages', false),
    imagesExcludeWebp: config.imagesExcludeWebp ?? fieldDefault('imagesExcludeWebp', false),
    imagesInputMaxBytes: config.imagesInputMaxBytes ?? fieldDefault('imagesInputMaxBytes', 20 * 1024 * 1024),
    imagesResizeMaxSide: config.imagesResizeMaxSide ?? fieldDefault('imagesResizeMaxSide', 1568),
    imagesResizeMaxBytes: config.imagesResizeMaxBytes ?? fieldDefault('imagesResizeMaxBytes', 500 * 1024),
    imagesResizeMinSide: config.imagesResizeMinSide ?? fieldDefault('imagesResizeMinSide', 200),
    imagesResizeJpegQuality: config.imagesResizeJpegQuality ?? fieldDefault('imagesResizeJpegQuality', 80),
  }
}

/**
 * Install the optional-settings consumer wiring for this plugin: while a
 * settings provider is mounted, resolve through the `tool-plus` namespace
 * (schema defaults → composition entry `base` → user document) and forward the
 * scope to `onSource`; when none is mounted, keep the composition entry, so
 * the tool keeps working exactly as composed. Mirrors the official bash-local
 * pattern so a committed change applies without a reload.
 * @param ctx - plugin context owning the wiring.
 * @param entry - composition entry config declared by the caller.
 * @param onSource - receives a thunk of the currently authoritative runtime config.
 */
export function installBashPlusSettings(
  ctx: Context,
  entry: Config,
  onSource: (current: () => RuntimeConfig) => void,
): void {
  // installSettingsSection 只在注册时调 setSource；scope 变化时只调 onChange。
  // 保存 setSource 的 thunk，onChange 时重新求值，否则 cfg 永不随设置更新
  // （用户改 editMode 等字段后 read/edit 行为不变）。
  let currentSource: (() => Config) | undefined
  installSettingsSection(ctx, BASH_PLUS_SETTINGS_NS, Config, entry, {
    setSource: (current) => {
      currentSource = current
      onSource(() => resolveConfig(current() as Config))
    },
    onChange: () => {
      const source = currentSource
      if (source) onSource(() => resolveConfig(source() as Config))
    },
  })
}
