/**
 * Locale bundles for the bash-plus settings card. zh is the source of truth
 * for the key set; en is checked complete against it — both dictionaries are
 * `Record<BashPlusLocaleKey, string>`, so a missing or extra key in either is
 * a compile error (the official registration enforces bilingual balance).
 * @module @xiaoso/dsh-tool-plus/client
 */

export type BashPlusLocaleKey =
  | 'title' | 'description'
  | 'nav' | 'pageTitle' | 'pageDescription'
  | 'tabBash' | 'tabRead' | 'tabWriteEdit' | 'tabGrep' | 'tabGlob' | 'tabAstGrep' | 'tabAstEdit' | 'tabReadImage'
  | 'groupTiming' | 'groupOutput' | 'groupTruncation' | 'groupBehavior'
  | 'groupReading' | 'groupSummary' | 'groupImages' | 'groupEditMode' | 'groupGuard' | 'groupGrep' | 'groupFetch' | 'groupAst'
  | 'noConfigTitle' | 'noConfigHint'
  | 'readSummarizeEnabled' | 'readSummarizeEnabledHint'
  | 'readSummarizeProse' | 'readSummarizeProseHint'
  | 'readSummarizeMinBodyLines' | 'readSummarizeMinBodyLinesHint'
  | 'readSummarizeMinCommentLines' | 'readSummarizeMinCommentLinesHint'
  | 'readSummarizeMinTotalLines' | 'readSummarizeMinTotalLinesHint'
  | 'readSummarizeUnfoldUntil' | 'readSummarizeUnfoldUntilHint'
  | 'readSummarizeUnfoldLimit' | 'readSummarizeUnfoldLimitHint'
  | 'editBlockAutoGenerated' | 'editBlockAutoGeneratedHint'
  | 'readDefaultLimit' | 'readDefaultLimitHint'
  | 'readLineNumbers' | 'readLineNumbersHint'
  | 'readRenderMarkdown' | 'readRenderMarkdownHint'
  | 'editMode' | 'editModeHint'
  | 'editFuzzyMatch' | 'editFuzzyMatchHint'
  | 'editFuzzyThreshold' | 'editFuzzyThresholdHint'
  | 'editEnforceSeenLines' | 'editEnforceSeenLinesHint'
  | 'grepContextBefore' | 'grepContextBeforeHint'
  | 'grepContextAfter' | 'grepContextAfterHint'
  | 'astGrepEnabled' | 'astGrepEnabledHint'
  | 'astEditEnabled' | 'astEditEnabledHint'
  | 'optAuto' | 'optReplace' | 'optPatch' | 'optHashline' | 'optApplyPatch'
  | 'fetchEnabled' | 'fetchEnabledHint'
  | 'fetchMaxTimeoutSeconds' | 'fetchMaxTimeoutSecondsHint'
  | 'imagesAutoResize' | 'imagesAutoResizeHint'
  | 'inspectImageMode' | 'inspectImageModeHint'
  | 'optOn' | 'optOff'
  | 'autoBackgroundMs' | 'autoBackgroundMsHint'
  | 'defaultTimeoutMs' | 'defaultTimeoutMsHint'
  | 'maxTimeoutMs' | 'maxTimeoutMsHint'
  | 'maxBackgroundJobs' | 'maxBackgroundJobsHint'
  | 'outputMaxBytes' | 'outputMaxBytesHint'
  | 'outputSinkTailBytes' | 'outputSinkTailBytesHint'
  | 'outputSinkHeadBytes' | 'outputSinkHeadBytesHint'
  | 'minimizerEnabled' | 'minimizerEnabledHint'
  | 'enableRunInBackground' | 'enableRunInBackgroundHint'
  | 'interceptorEnabled' | 'interceptorEnabledHint'
  | 'nonInteractiveEnv' | 'nonInteractiveEnvHint'
  | 'snapshotEnabled' | 'snapshotEnabledHint'
  | 'useShellCommandWrapper' | 'useShellCommandWrapperHint'
  | 'outputTruncateStrategy' | 'outputTruncateStrategyHint'
  | 'outputTruncateTriggerBytes' | 'outputTruncateTriggerBytesHint'
  | 'outputTruncateTriggerLines' | 'outputTruncateTriggerLinesHint'
  | 'outputTruncateByteMode' | 'outputTruncateByteModeHint'
  | 'outputTruncateByteHeadBytes' | 'outputTruncateByteHeadBytesHint'
  | 'outputTruncateByteTailBytes' | 'outputTruncateByteTailBytesHint'
  | 'outputTruncateLineMode' | 'outputTruncateLineModeHint'
  | 'outputTruncateLineHeadLines' | 'outputTruncateLineHeadLinesHint'
  | 'outputTruncateLineTailLines' | 'outputTruncateLineTailLinesHint'
  | 'optBytes' | 'optLines' | 'optHead' | 'optTail' | 'optMiddle'
  | 'overridden' | 'reset' | 'readOnly' | 'expand' | 'collapse'
  | 'save' | 'saving' | 'discard' | 'unsaved' | 'saveFailed' | 'invalidNumber'
  | 'appliesTo'

/** Simplified Chinese copy. */
export const zh: Record<BashPlusLocaleKey, string> = {
  title: 'Bash（bash-plus）',
  description: '持久化 shell 工具：超时、后台化、命令拦截与运行环境。',
  nav: 'Tool Plus',
  pageTitle: 'Tool Plus 工具配置',
  pageDescription: '按工具切换，调整每个工具的全局配置；保存后对新调用生效。',
  tabBash: 'Bash',
  tabRead: 'Read',
  tabWriteEdit: 'Write & Edit',
  tabGrep: 'Grep',
  tabGlob: 'Glob',
  tabAstGrep: 'Ast Grep',
  tabAstEdit: 'Ast Edit',
  tabReadImage: 'Read Image',
  groupTiming: '超时与后台',
  groupOutput: '输出',
  groupTruncation: '完成消息截断',
  groupBehavior: '行为',
    groupReading: '读取',
  groupSummary: '代码摘要',
  groupImages: '图片',
  groupEditMode: '编辑模式',
  groupGuard: '文件守卫',
  noConfigTitle: '该工具无全局配置项',
  noConfigHint: '该工具的行为完全由调用参数决定，无需在此调整。',
  readSummarizeEnabled: '代码摘要',
  readSummarizeEnabledHint: '读取长代码文件时自动生成结构性摘要（函数/类清单）。关闭后 read 返回原始全文。',
  readSummarizeProse: '散文式摘要',
  readSummarizeProseHint: '用自然语言段落描述文件的功能与导出，而非罗列函数/类的结构清单。',
  readSummarizeMinBodyLines: '正文最少行数',
  readSummarizeMinBodyLinesHint: '文件正文（去除注释/空行后）达到该行数才生成摘要。',
  readSummarizeMinCommentLines: '注释最少行数',
  readSummarizeMinCommentLinesHint: '注释行达到该数量才生成摘要。',
  readSummarizeMinTotalLines: '总行数阈值',
  readSummarizeMinTotalLinesHint: '文件总行数达到该值才触发摘要。',
  readSummarizeUnfoldUntil: '摘要展开阈值',
  readSummarizeUnfoldUntilHint: '文件行数不超过该值时，摘要中直接展开函数体。',
  readSummarizeUnfoldLimit: '摘要展开上限',
  readSummarizeUnfoldLimitHint: '摘要中最多展开的函数体数量，超出部分折叠为"…"。',
    readDefaultLimit: '默认读取行数',
  readDefaultLimitHint: 'read 未指定 :N-M 选择器时，默认输出行数的上限。',
  readLineNumbers: '默认显示行号',
  readLineNumbersHint: '为 read 输出默认添加行号前缀。',
    fetchEnabled: 'URL 抓取',
  fetchEnabledHint: 'read/write/grep 处理 http(s) URL 时是否启用抓取。',
  fetchMaxTimeoutSeconds: '抓取超时（秒）',
  fetchMaxTimeoutSecondsHint: 'URL 抓取超时上限；0 表示使用默认的 30 秒。',
  imagesAutoResize: '图片自动缩放',
  imagesAutoResizeHint: 'read 读取图片时自动缩放到可展示尺寸。',
  inspectImageMode: '图片检查模式',
  inspectImageModeHint: '读图工具的行为模式：auto/on/off。',
  groupFetch: '抓取',
  optOn: 'on（开启）',
  optOff: 'off（关闭）',
readRenderMarkdown: '渲染 Markdown',
  readRenderMarkdownHint: '读取 .md 文件时按 Markdown 渲染输出。',
  editMode: '编辑模式',
  editModeHint: 'edit 工具的输入解释模式：replace=字面量替换；patch=unified diff；hashline=行锚点补丁；apply_patch=Codex 信封。默认 replace。',
  editFuzzyMatch: '模糊匹配',
  editFuzzyMatchHint: '字面量替换未精确命中时启用相似度容错。',
  editFuzzyThreshold: '模糊匹配阈值',
  editFuzzyThresholdHint: '相似度阈值，低于该值不视为命中。',
  editEnforceSeenLines: '已见行守卫',
  editEnforceSeenLinesHint: '拒绝锚定在先前 read/search 从未完整展示过的行上的编辑。',
  grepContextBefore: '匹配前上下文行数',
  grepContextBeforeHint: '每个匹配前展示的上下文行数。',
  grepContextAfter: '匹配后上下文行数',
  grepContextAfterHint: '每个匹配后展示的上下文行数。',
  astGrepEnabled: '启用 ast_grep',
  astGrepEnabledHint: '启用 ast_grep 工具做结构化 AST 搜索（默认关闭）。',
  astEditEnabled: '启用 ast_edit',
  astEditEnabledHint: '启用 ast_edit 工具做结构化 AST 重写（默认开启）。',
  groupGrep: '匹配上下文',
  groupAst: 'AST 工具',
  optAuto: 'auto（自动）',
  optReplace: 'replace（字面量替换）',
  optPatch: 'patch（unified diff）',
  optHashline: 'hashline（行锚点）',
  optApplyPatch: 'apply_patch（Codex 信封）',
editBlockAutoGenerated: '阻止修改自动生成文件',
  editBlockAutoGeneratedHint: '拒绝编辑 / 覆盖自动生成的文件：文件名以 zz_generated. 开头，或属于 protobuf / 代码生成产物（.pb.go、_pb2.py、.gen.ts、generated.go、swagger/openapi.json、.mock.ts 等），或文件头含 @generated、code generated by、generated by protoc/sqlc/buf 等生成标记的文件，防止误改构建产物。',
  autoBackgroundMs: '自动后台阈值（毫秒）',
  autoBackgroundMsHint: '前台命令运行超过该时长会自动转入后台（0 表示关闭）。',
  defaultTimeoutMs: '默认超时（毫秒）',
  defaultTimeoutMsHint: '模型未指定 timeoutMs 时采用的默认命令超时（上限 1 小时）。',
  maxTimeoutMs: '最大超时上限（毫秒）',
  maxTimeoutMsHint: '对显式 timeoutMs 的上限钳制，超出的值会被截断到这个上限。',
  maxBackgroundJobs: '最大后台任务数',
  maxBackgroundJobsHint: '并发后台任务上限，超出即拒绝新任务。',
  outputMaxBytes: '输出预算（字节）',
  outputMaxBytesHint: '实时预览与后台任务读取的保留输出预算，超出部分写入 spill 文件。',
  outputSinkTailBytes: '尾部窗口（字节）',
  outputSinkTailBytesHint: '输出滚动保留的尾部窗口大小。',
  outputSinkHeadBytes: '开头窗口（字节）',
  outputSinkHeadBytesHint: '尾部之外额外保留的开头窗口大小。',
  minimizerEnabled: '输出最小化',
  minimizerEnabledHint: '用原生智能压缩处理 git / npm / cargo 等命令的长输出。',
  enableRunInBackground: '允许模型主动执行后台 bash 任务',
  enableRunInBackgroundHint: '开启后，模型可主动让长任务转入后台执行，完成时自动收到结果；关闭则只能前台等待。',
  interceptorEnabled: '命令拦截',
  interceptorEnabledHint: '拦截 cat / grep / find / sed -i 这类命令，并建议改用对应的专用工具。',
  nonInteractiveEnv: '非交互式环境',
  nonInteractiveEnvHint: '对非交互使用加固环境：关闭分页器与彩色输出，不弹交互提示。',
  snapshotEnabled: 'Shell 快照',
  snapshotEnabledHint: '把用户的 rc 文件（别名、函数、选项）快照进会话 shell。',
  useShellCommandWrapper: '用 bash -c 包裹命令',
  useShellCommandWrapperHint: '把每条命令用 bash -c 包裹，以获得完整的 bash 环境。',
  outputTruncateStrategy: '截断按',
  outputTruncateStrategyHint: '后台任务完成消息达到阈值时的截断单位：按字节或按行。切换后下方显示对应单位的配置。',
  outputTruncateTriggerBytes: '字节触发阈值',
  outputTruncateTriggerBytesHint: '完成文本超过该字节数才截断（按字节策略时生效）。',
  outputTruncateTriggerLines: '行触发阈值',
  outputTruncateTriggerLinesHint: '完成文本超过该行数才截断（按行策略时生效）。',
  outputTruncateByteMode: '字节保留方式',
  outputTruncateByteModeHint: '截断后保留哪些字节：仅开头 / 仅结尾 / 头尾各保留一段（按字节策略时生效）。',
  outputTruncateByteHeadBytes: '字节保留 — 开头',
  outputTruncateByteHeadBytesHint: '开头（或头尾各留）模式下保留的开头字节数（仅结尾模式隐藏）。',
  outputTruncateByteTailBytes: '字节保留 — 结尾',
  outputTruncateByteTailBytesHint: '结尾（或头尾各留）模式下保留的结尾字节数（仅开头模式隐藏）。',
  outputTruncateLineMode: '行保留方式',
  outputTruncateLineModeHint: '截断后保留哪些行：仅开头 / 仅结尾 / 头尾各保留一段（按行策略时生效）。',
  outputTruncateLineHeadLines: '行保留 — 开头',
  outputTruncateLineHeadLinesHint: '开头（或头尾各留）模式下保留的开头行数（仅结尾模式隐藏）。',
  outputTruncateLineTailLines: '行保留 — 结尾',
  outputTruncateLineTailLinesHint: '结尾（或头尾各留）模式下保留的结尾行数（仅开头模式隐藏）。',
  optBytes: '按字节',
  optLines: '按行',
  optHead: '仅开头',
  optTail: '仅结尾',
  optMiddle: '头尾各留',
  overridden: '已覆盖',
  reset: '恢复默认',
  readOnly: '本部署的设置为只读。',
  expand: '展开设置',
  collapse: '收起设置',
  save: '保存',
  saving: '保存中…',
  discard: '放弃修改',
  unsaved: '未保存',
  saveFailed: '本部署没有接受这些值，已保留供你修改。',
  invalidNumber: '请填写数字；留空表示使用默认值。',
  appliesTo: '保存后对新调用生效。',
}

/** English copy. */
export const en: Record<BashPlusLocaleKey, string> = {
  title: 'Bash (bash-plus)',
  description: 'Persistent shell tool: timeouts, backgrounding, interception, and environment.',
  nav: 'Tool Plus',
  pageTitle: 'Tool Plus tool configuration',
  pageDescription: 'Switch by tool to adjust its global settings; values apply to new calls.',
  tabBash: 'Bash',
  tabRead: 'Read',
  tabWriteEdit: 'Write & Edit',
  tabGrep: 'Grep',
  tabGlob: 'Glob',
  tabAstGrep: 'Ast Grep',
  tabAstEdit: 'Ast Edit',
  tabReadImage: 'Read Image',
  groupTiming: 'Timeouts & backgrounding',
  groupOutput: 'Output',
  groupTruncation: 'Completion truncation',
  groupBehavior: 'Behavior',  groupReading: 'Reading',
  groupSummary: 'Code summary',
  groupImages: 'Images',
  groupEditMode: 'Edit mode',
  groupGuard: 'File guard',

  noConfigTitle: 'No global settings for this tool',
  noConfigHint: 'Its behavior is fully driven by call arguments; nothing to adjust here.',
  readSummarizeEnabled: 'Code summary',
  readSummarizeEnabledHint: 'Automatically summarize long code files (function/class inventory) when reading. Off returns the raw text.',
  readSummarizeProse: 'Prose summary',
  readSummarizeProseHint: 'Describe what the file does and exports in natural-language paragraphs instead of a structural function/class list.',
  readSummarizeMinBodyLines: 'Min body lines',
  readSummarizeMinBodyLinesHint: 'Only summarize when the file body (excluding comments/blank lines) reaches this many lines.',
  readSummarizeMinCommentLines: 'Min comment lines',
  readSummarizeMinCommentLinesHint: 'Only summarize when comment lines reach this count.',
  readSummarizeMinTotalLines: 'Total line threshold',
  readSummarizeMinTotalLinesHint: 'Only summarize when the file reaches this total line count.',
  readSummarizeUnfoldUntil: 'Unfold threshold',
  readSummarizeUnfoldUntilHint: 'Expand function bodies directly while the file is at most this many lines.',
  readSummarizeUnfoldLimit: 'Unfold limit',
  readSummarizeUnfoldLimitHint: 'Maximum number of function bodies expanded in one summary; the rest collapse to "…".',
    readDefaultLimit: 'Default read limit',
  readDefaultLimitHint: 'Default cap on read output lines when no :N-M selector is given.',
  readLineNumbers: 'Line numbers by default',
  readLineNumbersHint: 'Prepend line numbers to read output by default.',
  fetchEnabled: 'URL fetching',
  fetchEnabledHint: 'Whether fetching is enabled when read/write/grep handle http(s) URLs.',
  fetchMaxTimeoutSeconds: 'Fetch timeout (s)',
  fetchMaxTimeoutSecondsHint: 'URL fetch timeout cap; 0 = default 30s.',
  imagesAutoResize: 'Auto-resize images',
  imagesAutoResizeHint: 'Auto-resize images to a displayable size when reading.',
  inspectImageMode: 'Image inspection mode',
  inspectImageModeHint: 'Behavior mode for inspecting images: auto/on/off.',
  groupFetch: 'Fetching',
  optOn: 'on',
  optOff: 'off',
  readRenderMarkdown: 'Render Markdown',
  readRenderMarkdownHint: 'Render .md files as Markdown when reading.',
  editMode: 'Edit mode',
  editModeHint: 'How edit interprets its input: replace / patch / hashline / apply_patch. Default: replace.',
  editFuzzyMatch: 'Fuzzy matching',
  editFuzzyMatchHint: 'Tolerate similarity mismatches for literal replacements.',
  editFuzzyThreshold: 'Fuzzy threshold',
  editFuzzyThresholdHint: 'Similarity threshold below which a match is not accepted.',
  editEnforceSeenLines: 'Seen-line guard',
  editEnforceSeenLinesHint: 'Reject edits anchored on lines a prior read/search never displayed in full.',
  grepContextBefore: 'Context lines before match',
  grepContextBeforeHint: 'Context lines shown before each match.',
  grepContextAfter: 'Context lines after match',
  grepContextAfterHint: 'Context lines shown after each match.',
  astGrepEnabled: 'Enable ast_grep',
  astGrepEnabledHint: 'Enable the ast_grep tool for structural AST search (off by default).',
  astEditEnabled: 'Enable ast_edit',
  astEditEnabledHint: 'Enable the ast_edit tool for structural AST rewrites (on by default).',
  groupGrep: 'Match context',
  groupAst: 'AST tools',
  optAuto: 'auto',
  optReplace: 'replace (literal)',
  optPatch: 'patch (unified diff)',
  optHashline: 'hashline (line anchors)',
  optApplyPatch: 'apply_patch (Codex envelope)',
editBlockAutoGenerated: 'Block editing auto-generated files',
  editBlockAutoGeneratedHint: 'Refuse edits / overwrites of auto-generated files: names starting with zz_generated., protobuf / codegen artifacts (.pb.go, _pb2.py, .gen.ts, generated.go, swagger/openapi.json, .mock.ts, …), or files whose header carries generation markers (@generated, "code generated by", "generated by protoc/sqlc/buf", …) — protecting build artifacts.',
  autoBackgroundMs: 'Auto-background threshold (ms)',
  autoBackgroundMsHint: 'Foreground commands running longer move to the background automatically (0 disables).',
  defaultTimeoutMs: 'Default timeout (ms)',
  defaultTimeoutMsHint: 'Deadline applied when the model omits timeoutMs (capped at 1 hour).',
  maxTimeoutMs: 'Max timeout clamp (ms)',
  maxTimeoutMsHint: 'Upper clamp for explicit timeouts; larger values are cut down to this limit.',
  maxBackgroundJobs: 'Max background jobs',
  maxBackgroundJobsHint: 'Concurrent background job cap; extra requests are rejected.',
  outputMaxBytes: 'Output budget (bytes)',
  outputMaxBytesHint: 'Retained output budget for live previews and background reads; overflow spills to a file.',
  outputSinkTailBytes: 'Tail window (bytes)',
  outputSinkTailBytesHint: 'Rolling tail window the output sink keeps.',
  outputSinkHeadBytes: 'Head window (bytes)',
  outputSinkHeadBytesHint: 'Leading window kept in addition to the tail.',
  minimizerEnabled: 'Output minimizer',
  minimizerEnabledHint: 'Native intelligent compression for git / npm / cargo long outputs.',
  enableRunInBackground: 'Allow the model to run background bash tasks',
  enableRunInBackgroundHint: 'When on, the model can proactively move long-running commands to the background and receives the result automatically; when off, everything runs in the foreground.',
  interceptorEnabled: 'Command interception',
  interceptorEnabledHint: 'Block cat / grep / find / sed -i style commands and suggest the dedicated tool instead.',
  nonInteractiveEnv: 'Non-interactive environment',
  nonInteractiveEnvHint: 'Harden the environment for non-interactive use: no pagers, no prompts, no color.',
  snapshotEnabled: 'Shell snapshot',
  snapshotEnabledHint: "Capture the user's rc file (aliases, functions, options) into the session shell.",
  useShellCommandWrapper: 'Wrap commands in bash -c',
  useShellCommandWrapperHint: 'Wrap every command in bash -c for a full bash environment.',
  outputTruncateStrategy: 'Truncate by',
  outputTruncateStrategyHint: 'Unit used when a background completion message crosses its threshold: bytes or lines. Switching shows the matching unit\'s settings below.',
  outputTruncateTriggerBytes: 'Byte trigger threshold',
  outputTruncateTriggerBytesHint: 'Truncate only when the completion text exceeds this many bytes (byte strategy).',
  outputTruncateTriggerLines: 'Line trigger threshold',
  outputTruncateTriggerLinesHint: 'Truncate only when the completion text exceeds this many lines (line strategy).',
  outputTruncateByteMode: 'Byte retention mode',
  outputTruncateByteModeHint: 'Which bytes to keep after truncation: head only, tail only, or both (byte strategy).',
  outputTruncateByteHeadBytes: 'Byte retention — head',
  outputTruncateByteHeadBytesHint: 'Leading bytes kept in head (or middle) mode; hidden in tail-only mode.',
  outputTruncateByteTailBytes: 'Byte retention — tail',
  outputTruncateByteTailBytesHint: 'Trailing bytes kept in tail (or middle) mode; hidden in head-only mode.',
  outputTruncateLineMode: 'Line retention mode',
  outputTruncateLineModeHint: 'Which lines to keep after truncation: head only, tail only, or both (line strategy).',
  outputTruncateLineHeadLines: 'Line retention — head',
  outputTruncateLineHeadLinesHint: 'Leading lines kept in head (or middle) mode; hidden in tail-only mode.',
  outputTruncateLineTailLines: 'Line retention — tail',
  outputTruncateLineTailLinesHint: 'Trailing lines kept in tail (or middle) mode; hidden in head-only mode.',
  optBytes: 'Bytes',
  optLines: 'Lines',
  optHead: 'Head only',
  optTail: 'Tail only',
  optMiddle: 'Head and tail',
  overridden: 'Overridden',
  reset: 'Reset to default',
  readOnly: 'This deployment stores settings read-only.',
  expand: 'Show settings',
  collapse: 'Hide settings',
  save: 'Save',
  saving: 'Saving…',
  discard: 'Discard',
  unsaved: 'Unsaved',
  saveFailed: 'The deployment did not accept these values; they were left for you to correct.',
  invalidNumber: 'Enter a number, or leave blank to use the default.',
  appliesTo: 'Values apply to new calls.',
}

/** Merge this plugin's namespace into the slot locale table (official pattern). */
declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap {
    /** This plugin's own settings-card copy. */
    'tool-plus': BashPlusLocaleKey
  }
}
