/**
 * auto-generated 守卫：单实现的行为契约 + 两条调用面回归。
 *
 * A-3（second-impl-audit.md）：仓库里曾并存两份 auto-generated-guard ——
 * `src/tools/edit/adapter/tools/auto-generated-guard.ts`（上游逐字移植，hashline
 * 路径在用）与 `src/tools/shared/auto-generated-guard.dsh.ts`（简化重写，write/patch
 * 在用）。修复方向是删掉简化版、全走逐字版，并保留 T17-1 的 basename 反斜杠修复
 * （逐字版缺失）。本文件覆盖：
 *  1. 守卫报错含上游完整三步整改文案（model-facing recoverable message）；
 *  2. T17-1：Windows 反斜杠路径的 basename 识别不被破坏（无头注释也按文件名拦截）；
 *  3. 两个调用面（write/patch 与 hashline）行为一致；
 *  4. write 工具这一面：已存在的 `zz_generated.go` 被拒绝改写（T17-1 回归）。
 * @module tests
 */

import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { assertEditableFile, setBlockAutoGenerated } from '../../src/tools/shared/auto-generated-guard.dsh.ts'
import { assertEditableFile as assertEditableFileVerbatim } from '../../src/tools/edit/adapter/tools/auto-generated-guard.ts'
import { executeWriteTool } from '../../src/tools/write/adapter/index.ts'

const tmpDirs: string[] = []
function tmpDir(prefix: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix))
  tmpDirs.push(dir)
  return dir
}
afterEach(() => {
  for (const dir of tmpDirs.splice(0)) fs.rmSync(dir, { recursive: true, force: true })
})

/** Minimal tool execution context: only the session cwd is read. */
function execFor(cwd: string): any {
  return { agent: { session: { header: { cwd } } }, signal: undefined }
}

describe('auto-generated-guard 双实现合并（A-3）', () => {
  beforeEach(() => {
    setBlockAutoGenerated(true)
  })

  it('守卫报错含上游完整三步整改文案（write/patch 路径不再截断）', async () => {
    const dir = tmpDir('ag-guard-')
    const file = path.join(dir, 'zz_generated.go')
    fs.writeFileSync(file, '// Code generated by protoc. DO NOT EDIT.\npackage main\n')

    const err = await assertEditableFile(file).then(
      () => null,
      (e: Error) => e,
    )
    expect(err).not.toBeNull()
    // 上游 refs tools/auto-generated-guard.ts:232-241 的完整文案
    expect(err!.message).toContain('Instead:')
    expect(err!.message).toContain('1. Find the source file or generator configuration')
    expect(err!.message).toContain('2. Make changes to the source')
    expect(err!.message).toContain('3. Regenerate the file')
  })

  it('T17-1：basename 兼容反斜杠路径（文件名模式命中，无头注释也拦截）', async () => {
    const dir = tmpDir('ag-guard-')
    const file = path.join(dir, 'zz_generated.go')
    // 无 auto-generated 头注释——只能靠文件名模式（zz_generated.go）拦截
    fs.writeFileSync(file, 'package main\n\nfunc main() {}\n')

    const err = await assertEditableFile(file, 'some\\dir\\zz_generated.go').then(
      () => null,
      (e: Error) => e,
    )
    expect(err).not.toBeNull()
  })

  it('两个调用面行为一致（同输入同结论，文案一致）', async () => {
    const dir = tmpDir('ag-guard-')
    const file = path.join(dir, 'zz_generated.go')
    fs.writeFileSync(file, '// Code generated by protoc. DO NOT EDIT.\npackage main\n')

    const errShared = await assertEditableFile(file).then(
      () => null,
      (e: Error) => e,
    )
    const errVerbatim = await assertEditableFileVerbatim(file).then(
      () => null,
      (e: Error) => e,
    )
    expect(errShared).not.toBeNull()
    expect(errVerbatim).not.toBeNull()
    // 合并后同一实现：文案必须一致（旧 shared 版截断了整改指引）
    expect(errShared!.message).toBe(errVerbatim!.message)
  })
})

describe('write auto-generated 守卫（T17-1）', () => {
  beforeEach(() => {
    // 默认就是拦截；这里显式打开，免得受同文件其它 describe 的状态影响。
    setBlockAutoGenerated(true)
  })

  it('`zz_generated.go`（已存在）被拒绝改写', async () => {
    // OMP 的 isAutoGeneratedFileName 用 `filePath.split('/').pop()` 取 basename，
    // Windows 反斜杠路径整串不匹配 `/^zz_generated\./`，守卫会静默放行。
    const dir = tmpDir('tool-plus-guard-')
    const file = path.join(dir, 'zz_generated.go')
    fs.writeFileSync(file, '// original\n')

    await expect(
      executeWriteTool(execFor(dir), {} as never, { path: file, content: '// x' }),
    ).rejects.toThrow(/auto-generated/i)
  })
})
