/**
 * A-3 回归：auto-generated-guard 双实现合并。
 *
 * 背景（second-impl-audit.md A-3）：仓库内并存两份 auto-generated-guard——
 * `src/tools/edit/adapter/tools/auto-generated-guard.ts`（335 行，上游逐字移植，
 * hashline 路径在用）与 `src/tools/shared/auto-generated-guard.dsh.ts`（简化
 * 重写，write/patch 路径在用：SimpleLRU、手搓 peekFile、截断整改文案、推送
 * 开关）。修复方向：删简化版、全走逐字版（单一实现），并保留 T17-1 的
 * basename 反斜杠修复（逐字版缺失）。
 *
 * 本文件断言合并后的行为契约：
 *  1. 守卫报错含上游完整三步整改文案（model-facing recoverable message）；
 *  2. T17-1：Windows 反斜杠路径的 basename 识别不被破坏（zz_generated.go
 *     无头注释也应被文件名模式拦截）；
 *  3. 两个调用面（write/patch 与 hashline）行为一致。
 */
import { beforeEach, describe, expect, it } from 'vitest'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { assertEditableFile, setBlockAutoGenerated } from '../../src/tools/shared/auto-generated-guard.dsh.ts'
import { assertEditableFile as assertEditableFileVerbatim } from '../../src/tools/edit/adapter/tools/auto-generated-guard.ts'

const tmpDirs: string[] = []
function tmpDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ag-guard-'))
  tmpDirs.push(dir)
  return dir
}

describe('auto-generated-guard 双实现合并（A-3）', () => {
  beforeEach(() => {
    setBlockAutoGenerated(true)
  })

  it('守卫报错含上游完整三步整改文案（write/patch 路径不再截断）', async () => {
    const dir = tmpDir()
    const file = path.join(dir, 'zz_generated.go')
    fs.writeFileSync(file, '// Code generated by protoc. DO NOT EDIT.\npackage main\n')

    const err = await assertEditableFile(file).then(
      () => null,
      (e: Error) => e,
    )
    expect(err).not.toBeNull()
    // 上游 refs tools/auto-generated-guard.ts:232-241 的完整文案
    expect(err!.message).toContain('Instead:')
    expect(err!.message).toContain('1. Find the source file or generator configuration')
    expect(err!.message).toContain('2. Make changes to the source')
    expect(err!.message).toContain('3. Regenerate the file')
  })

  it('T17-1：basename 兼容反斜杠路径（文件名模式命中，无头注释也拦截）', async () => {
    const dir = tmpDir()
    const file = path.join(dir, 'zz_generated.go')
    // 无 auto-generated 头注释——只能靠文件名模式（zz_generated.go）拦截
    fs.writeFileSync(file, 'package main\n\nfunc main() {}\n')

    const err = await assertEditableFile(file, 'some\\dir\\zz_generated.go').then(
      () => null,
      (e: Error) => e,
    )
    expect(err).not.toBeNull()
  })

  it('两个调用面行为一致（同输入同结论，文案一致）', async () => {
    const dir = tmpDir()
    const file = path.join(dir, 'zz_generated.go')
    fs.writeFileSync(file, '// Code generated by protoc. DO NOT EDIT.\npackage main\n')

    const errShared = await assertEditableFile(file).then(
      () => null,
      (e: Error) => e,
    )
    const errVerbatim = await assertEditableFileVerbatim(file).then(
      () => null,
      (e: Error) => e,
    )
    expect(errShared).not.toBeNull()
    expect(errVerbatim).not.toBeNull()
    // 合并后同一实现：文案必须一致（旧 shared 版截断了整改指引）
    expect(errShared!.message).toBe(errVerbatim!.message)
  })
})