/**
 * Native adapter surface — compat-layer coverage.
 *
 * `src/tools/hashline/native/index.ts` is the seam between DSH and the Rust
 * `@oh-my-pi/pi-natives` bindings: it re-exports the native transport, keeps
 * the deleted TS engine's display helpers and line-ending/BOM ports, and owns
 * the session store accessor plus the throw-based `MismatchError`. The migrated
 * engine suites under `src/tools/hashline/test/**` exercise that seam
 * behaviourally; this spec pins the **surface itself** — every runtime export
 * is callable and returns its documented observable result, so a renamed,
 * dropped or silently degraded re-export cannot hide behind the engine suites.
 *
 * Contract under test:
 *  - `HL_*` constants and the format helpers (`formatHashlineHeader`,
 *    `formatNumberedLines`, `formatNumberedLine`, `splitAddressableFileLines`,
 *    `stripHashlinePrefixes`, `computeFileHash`)
 *  - `getEditStore` (lazy creation + memoization on the owner object) and
 *    `MismatchError` (`message === displayMessage`, `name`, `instanceof Error`)
 *  - every native re-export: `blockRangeAt`, `buildCompactDiffPreview`,
 *    `detectLineEnding`, `normalizeToLF`, `restoreLineEndings`, `stripBom`,
 *    `editAutoGeneratedMessage`, `editDescription`, `editDiffString`,
 *    `editGrammar`, `editInspect`, `hashlineCountOps`, `structuredPatchHunks`,
 *    `EditStore` (full method set), `EditSession` (apply + rejection lifecycle)
 *  - the vendored fixture corpus driven through a real `EditStore` +
 *    `EditSession`: every payload-bearing case must COMPLETE through the
 *    adapter (an engine rejection is a legitimate completion; a throw is not),
 *    and the unreachable cases are enumerated with their reason.
 *
 * Deliberately not a duplicate of `src/tools/hashline/test/hashline-fixtures.test.ts`:
 * that spec asserts the fixtures' exact expected bytes; this one asserts the
 * compat-layer call itself works and reports the reachable boundary.
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, describe, expect, it } from "vitest";

import * as adapter from "../../src/tools/hashline/native/index.ts";
import {
	blockRangeAt,
	buildCompactDiffPreview,
	computeFileHash,
	detectLineEnding,
	EditSession,
	EditStore,
	editAutoGeneratedMessage,
	editDescription,
	editDiffString,
	editGrammar,
	editInspect,
	formatHashlineHeader,
	formatNumberedLine,
	formatNumberedLines,
	getEditStore,
	hashlineCountOps,
	HL_FILE_HASH_LENGTH,
	HL_FILE_HASH_SEP,
	HL_FILE_PREFIX,
	HL_FILE_SUFFIX,
	HL_LINE_BODY_SEP,
	HL_MOVE_KEYWORD,
	HL_REM_KEYWORD,
	MismatchError,
	normalizeToLF,
	restoreLineEndings,
	splitAddressableFileLines,
	stripBom,
	stripHashlinePrefixes,
	structuredPatchHunks,
} from "../../src/tools/hashline/native/index.ts";
import type { EditPolicy, EditWriteRequest, EditWriteResponse } from "../../src/tools/hashline/native/index.ts";

/* -------------------------------------------------------------------------- */
/* Temp workspace + disk writer                                               */
/* -------------------------------------------------------------------------- */

const RAW_ROOT = fs.mkdtempSync(path.join(os.tmpdir(), "native-adapter-surface-"));
const ROOT = fs.realpathSync.native(RAW_ROOT);
const FIXTURE_DIR = fileURLToPath(new URL("../../src/tools/hashline/test/fixtures", import.meta.url));

let caseSeq = 0;

/** One case's real on-disk directory plus an isolated store. */
function makeCase(label: string): { dir: string; store: EditStore } {
	const dir = path.join(ROOT, `${String(caseSeq++).padStart(3, "0")}-${label.replace(/[^A-Za-z0-9._-]+/g, "_").slice(0, 40)}`);
	fs.mkdirSync(dir, { recursive: true });
	return { dir, store: new EditStore() };
}

function policyFor(cwd: string, overrides: Partial<EditPolicy> = {}): EditPolicy {
	return {
		cwd,
		mode: "hashline",
		allowFuzzy: true,
		fuzzyThreshold: 0.95,
		enforceSeenLines: false,
		blockAutoGenerated: true,
		planActive: false,
		homeDir: cwd,
		rawInput: false,
		...overrides,
	};
}

/** Disk-backed writer: `delete` unlinks, `move` writes+unlinks, else writes. */
function diskWriter(): { requests: EditWriteRequest[]; fn: (error: Error | null, request: EditWriteRequest) => Promise<EditWriteResponse> } {
	const requests: EditWriteRequest[] = [];
	const fn = async (error: Error | null, request: EditWriteRequest): Promise<EditWriteResponse> => {
		if (error) throw error;
		requests.push(request);
		if (request.op === "delete") {
			fs.rmSync(request.path, { force: true });
			return { written: "" };
		}
		const text = request.content ?? "";
		const target = request.moveTo ?? request.path;
		fs.mkdirSync(path.dirname(target), { recursive: true });
		fs.writeFileSync(target, text, "utf8");
		if (request.moveTo) fs.rmSync(request.path, { force: true });
		return { written: text };
	};
	return { requests, fn };
}

/** Drive one payload through the adapter's session lifecycle. */
async function applyInput(
	store: EditStore,
	cwd: string,
	input: string,
	policy: Partial<EditPolicy> = {},
): Promise<{ text: string; isError: boolean; files: unknown[] }> {
	const writer = diskWriter();
	const session = new EditSession(store, policyFor(cwd, policy), null);
	try {
		session.setArgsJson(JSON.stringify({ input }));
		session.finish();
		return (await session.apply({ lspFlush: false }, writer.fn)) as { text: string; isError: boolean; files: unknown[] };
	} finally {
		session.close();
	}
}

afterAll(() => {
	fs.rmSync(RAW_ROOT, { recursive: true, force: true });
});

/* -------------------------------------------------------------------------- */
/* 1. Display / format surface                                                */
/* -------------------------------------------------------------------------- */

describe("adapter display surface", () => {
	it("exposes the hashline wire-format constants", () => {
		expect(HL_FILE_PREFIX).toBe("[");
		expect(HL_FILE_SUFFIX).toBe("]");
		expect(HL_FILE_HASH_SEP).toBe("#");
		expect(HL_FILE_HASH_LENGTH).toBe(4);
		expect(HL_MOVE_KEYWORD).toBe("MV");
		expect(HL_REM_KEYWORD).toBe("REM");
		expect(HL_LINE_BODY_SEP).toBe(":");
	});

	it("composes a section header from the constants", () => {
		expect(formatHashlineHeader("src/a.ts", "1A2B")).toBe("[src/a.ts#1A2B]");
		expect(formatHashlineHeader("a.ts", "1A2B")).toBe(
			`${HL_FILE_PREFIX}a.ts${HL_FILE_HASH_SEP}1A2B${HL_FILE_SUFFIX}`,
		);
	});

	it("numbers display rows, with and without an explicit start line", () => {
		expect(formatNumberedLines("a\nb")).toBe("1:a\n2:b");
		expect(formatNumberedLines("a\nb", 5)).toBe("5:a\n6:b");
		expect(formatNumberedLine(3, "x")).toBe("3:x");
	});

	it("splits addressable rows and drops only the trailing-newline sentinel", () => {
		expect(splitAddressableFileLines("a\nb\n")).toEqual(["a", "b"]);
		expect(splitAddressableFileLines("a\nb")).toEqual(["a", "b"]);
		expect(splitAddressableFileLines("a\n\n")).toEqual(["a", ""]);
		expect(splitAddressableFileLines("a")).toEqual(["a"]);
		expect(splitAddressableFileLines("")).toEqual([]);
	});

	it("strips display prefixes from pasted rows, leaving mixed content alone", () => {
		expect(stripHashlinePrefixes(["1:a", "2:b"])).toEqual(["a", "b"]);
		expect(stripHashlinePrefixes(["1:one", "plain"])).toEqual(["1:one", "plain"]);
		expect(stripHashlinePrefixes([])).toEqual([]);
	});

	it("mints a stable 4-hex content tag that matches the store's snapshot tag", () => {
		const text = "before\n";
		const hash = computeFileHash(text);
		expect(hash).toMatch(/^[0-9A-F]{4}$/);
		expect(computeFileHash(text)).toBe(hash);
		expect(computeFileHash("after\n")).not.toBe(hash);

		const { dir, store } = makeCase("hash-parity");
		const abs = path.join(dir, "a.txt");
		fs.writeFileSync(abs, text);
		expect(store.recordSnapshot(abs, text)).toBe(hash);
	});
});

/* -------------------------------------------------------------------------- */
/* 2. Session store accessor + error type                                     */
/* -------------------------------------------------------------------------- */

describe("adapter session store and error type", () => {
	it("creates the store lazily and memoizes it on the owner object", () => {
		const owner: { editStore?: EditStore } = {};
		expect(owner.editStore).toBeUndefined();
		const first = getEditStore(owner);
		expect(first).toBeInstanceOf(EditStore);
		expect(owner.editStore).toBe(first);
		expect(getEditStore(owner)).toBe(first);
		expect(getEditStore({})).not.toBe(first);
	});

	it("drives every EditStore accessor through one path's lifecycle", () => {
		const { dir, store } = makeCase("store-lifecycle");
		const abs = path.join(dir, "demo.ts");
		const text = "function f() {\n  const a = 1;\n}\n";
		fs.writeFileSync(abs, text);

		const tag = store.recordSnapshot(abs, text, [1, 2]);
		expect(tag).toBe(computeFileHash(text));
		expect(store.headHash(abs)).toBe(tag);
		expect(store.headText(abs)).toBe(text);
		expect(store.byHashText(abs, tag)).toBe(text);
		expect(store.byHashText(abs, "0000")).toBeNull();
		expect(store.seenLines(abs, tag)).toEqual([1, 2]);
		expect(store.seenLines(abs, "0000")).toBeNull();

		const moved = path.join(dir, "moved.ts");
		store.relocate(abs, moved);
		expect(store.byHashText(moved, tag)).toBe(text);
		expect(store.byHashText(abs, tag)).toBeNull();

		store.invalidate(moved);
		expect(store.headHash(moved)).toBeNull();

		store.recordSnapshot(moved, text);
		store.clear();
		expect(store.headHash(moved)).toBeNull();
		expect(store.byHashText(moved, tag)).toBeNull();
	});

	it("carries the native rejection text through MismatchError unchanged", () => {
		const error = new MismatchError("Edit rejected for a.ts: hash #FFFF is not from this session.");
		expect(error).toBeInstanceOf(Error);
		expect(error).toBeInstanceOf(MismatchError);
		expect(error.name).toBe("MismatchError");
		expect(error.message).toBe("Edit rejected for a.ts: hash #FFFF is not from this session.");
		expect(error.displayMessage).toBe(error.message);
	});
});

/* -------------------------------------------------------------------------- */
/* 3. Native re-exports                                                       */
/* -------------------------------------------------------------------------- */

describe("adapter native re-exports", () => {
	it("resolves a block span with blockRangeAt and declines unknown input", () => {
		const code = "function f() {\n  const a = 1;\n}\n";
		expect(blockRangeAt({ code, path: "demo.ts", line: 2 })).toEqual({ startLine: 2, endLine: 2 });
		expect(blockRangeAt({ code, path: "demo.unknownlang", line: 2 })).toBeNull();
		expect(blockRangeAt({ code, path: "demo.ts", line: 99 })).toBeNull();
	});

	it("renders a compact diff preview with counts", () => {
		expect(buildCompactDiffPreview(" 1|alpha\n-2|beta\n+2|DELTA\n+3|EPSILON\n 3|gamma")).toEqual({
			preview: "1:alpha\n2:DELTA\n3:EPSILON\n4:gamma",
			addedLines: 2,
			removedLines: 1,
		});
	});

	it("ports the line-ending and BOM helpers", () => {
		expect(detectLineEnding("a\r\nb\nc")).toBe("\r\n");
		expect(detectLineEnding("a\nb\r\nc")).toBe("\n");
		expect(normalizeToLF("a\r\nb\rc\n")).toBe("a\nb\nc\n");
		expect(restoreLineEndings("a\nb", "\r\n")).toBe("a\r\nb");
		expect(restoreLineEndings("a\nb", "\n")).toBe("a\nb");
		expect(stripBom("\uFEFFx")).toEqual({ bom: "\uFEFF", text: "x" });
		expect(stripBom("x")).toEqual({ bom: "", text: "x" });
	});

	it("reports an editable plain temp file through editAutoGeneratedMessage", () => {
		const { dir } = makeCase("auto-generated");
		const abs = path.join(dir, "demo.ts");
		fs.writeFileSync(abs, "const a = 1;\n");
		expect(editAutoGeneratedMessage(abs, "demo.ts")).toBeNull();
	});

	it("returns the hashline description and lark grammar, and rejects an unknown mode", () => {
		const description = editDescription("hashline");
		expect(typeof description).toBe("string");
		expect(description.length).toBeGreaterThan(100);
		expect(description).toContain("Line-anchored patch language");

		const grammar = editGrammar("hashline");
		expect(typeof grammar).toBe("string");
		expect(grammar).toContain("begin_patch");
		expect(grammar).toContain("*** Begin Patch");
		expect(() => editGrammar("no-such-mode")).toThrow(/Unknown edit mode: no-such-mode/);
	});

	it("produces a numbered diff and structured hunks", () => {
		expect(editDiffString("a\nb\n", "a\nB\n")).toEqual({ diff: " 1|a\n-2|b\n+2|B", firstChangedLine: 2 });
		expect(structuredPatchHunks("a\nb\n", "a\nB\n")).toEqual([
			{ oldStart: 1, oldLines: 2, newStart: 1, newLines: 2, lines: [" a", "-b", "+B"] },
		]);
	});

	it("projects paths, matcher digests and file ops through editInspect", () => {
		expect(editInspect("hashline", JSON.stringify({ input: "[a.ts#F27C]\nPUT 1.=1:\n+x" }))).toEqual({
			paths: ["a.ts"],
			entries: [{ path: "a.ts", digest: "x" }],
			fileOps: [],
		});
		expect(editInspect("hashline", JSON.stringify({ input: "[r.txt#F27C]\nREM" })).fileOps).toEqual([
			{ kind: "delete", path: "r.txt" },
		]);
		expect(editInspect("hashline", JSON.stringify({ input: "[m.txt#F27C]\nMV dst/x.txt" })).fileOps).toEqual([
			{ kind: "move", path: "m.txt", to: "dst/x.txt" },
		]);
	});

	it("counts canonical op headers with hashlineCountOps", () => {
		expect(hashlineCountOps("PUT 1.=1:\n+x\nCUT 2.=3")).toEqual([
			{ label: "PUT N.=N:", count: 1 },
			{ label: "CUT N.=M", count: 1 },
		]);
		expect(hashlineCountOps("plain text")).toEqual([]);
	});

	it("exposes every runtime symbol the adapter promises", () => {
		const runtimeExports = [
			"HL_FILE_PREFIX",
			"HL_FILE_SUFFIX",
			"HL_FILE_HASH_SEP",
			"HL_FILE_HASH_LENGTH",
			"HL_MOVE_KEYWORD",
			"HL_REM_KEYWORD",
			"HL_LINE_BODY_SEP",
			"formatHashlineHeader",
			"formatNumberedLines",
			"formatNumberedLine",
			"splitAddressableFileLines",
			"stripHashlinePrefixes",
			"computeFileHash",
			"getEditStore",
			"MismatchError",
			"blockRangeAt",
			"buildCompactDiffPreview",
			"detectLineEnding",
			"EditStore",
			"EditSession",
			"editAutoGeneratedMessage",
			"editDescription",
			"editDiffString",
			"editGrammar",
			"editInspect",
			"hashlineCountOps",
			"normalizeToLF",
			"restoreLineEndings",
			"stripBom",
			"structuredPatchHunks",
		];
		expect(runtimeExports).toHaveLength(30);
		for (const name of runtimeExports) {
			expect(adapter[name as keyof typeof adapter], `missing runtime export: ${name}`).toBeDefined();
		}
	});
});

/* -------------------------------------------------------------------------- */
/* 4. EditSession lifecycle                                                   */
/* -------------------------------------------------------------------------- */

describe("adapter session lifecycle", () => {
	it("applies a payload and reports the landed bytes", async () => {
		const { dir, store } = makeCase("session-apply");
		const abs = path.join(dir, "a.ts");
		fs.writeFileSync(abs, "alpha\nbeta\n");
		const tag = store.recordSnapshot(abs, "alpha\nbeta\n");

		const outcome = await applyInput(store, dir, `[a.ts#${tag}]\nPUT 2.=2:\n+BETA`);
		expect(outcome.isError).toBe(false);
		expect(outcome.text).toContain("[a.ts#");
		expect(outcome.files).toHaveLength(1);
		expect(fs.readFileSync(abs, "utf8")).toBe("alpha\nBETA\n");
	});

	it("reports a rejected payload as an outcome instead of throwing", async () => {
		const { dir, store } = makeCase("session-reject");
		const abs = path.join(dir, "a.ts");
		fs.writeFileSync(abs, "alpha\nbeta\n");
		store.recordSnapshot(abs, "alpha\nbeta\n");

		const outcome = await applyInput(store, dir, "[a.ts#FFFF]\nPUT 1.=1:\n+x");
		expect(outcome.isError).toBe(true);
		expect(outcome.text).toContain("is not from this session");
		expect(fs.readFileSync(abs, "utf8")).toBe("alpha\nbeta\n");
	});
});

/* -------------------------------------------------------------------------- */
/* 5. Fixture corpus through the adapter                                      */
/* -------------------------------------------------------------------------- */

interface DriveCounts {
	patcherCases: number;
	applyCalls: number;
	unreachable: Array<{ fixture: string; case: string; reason: string }>;
}

const counts: DriveCounts = { patcherCases: 0, applyCalls: 0, unreachable: [] };

function loadFixture(name: string): any {
	return JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, name), "utf8"));
}

/** Absolute fixture paths collapse into the case directory (last two segments). */
function displayRel(rawPath: string): string {
	if (!path.isAbsolute(rawPath)) return rawPath.replace(/^[/\\]+/, "");
	const parts = rawPath.replace(/\\/g, "/").split("/").filter(Boolean);
	const tail = parts.slice(-2).join("/");
	return tail.includes(".") ? tail : parts[parts.length - 1] ?? "a.ts";
}

/** `patcher.json` case: files → snapshots → args, then assert the call completed. */
async function drivePatcherCase(caseData: Record<string, any>, label: string): Promise<void> {
	const { dir, store } = makeCase(label);
	for (const [rel, text] of Object.entries(caseData.files ?? {})) {
		const abs = path.join(dir, rel);
		fs.mkdirSync(path.dirname(abs), { recursive: true });
		fs.writeFileSync(abs, String(text), "utf8");
	}
	const tags: Array<[string, string]> = [];
	for (const snap of caseData.snapshots ?? []) {
		const rel = String(snap.path);
		const text = snap.text ?? fs.readFileSync(path.join(dir, rel), "utf8");
		tags.push([rel, store.recordSnapshot(path.join(dir, rel), String(text).replace(/\r\n?/g, "\n"), snap.seenLines ?? null)]);
	}
	let input = String(caseData.args?.input ?? "");
	for (const [rel, tag] of tags) input = input.split(`{{tag:${rel}}}`).join(tag);

	const policy: Partial<EditPolicy> = {};
	for (const key of ["allowFuzzy", "fuzzyThreshold", "enforceSeenLines", "planActive", "blockAutoGenerated"] as const) {
		if (caseData.policy?.[key] !== undefined) (policy as Record<string, unknown>)[key] = caseData.policy[key];
	}

	const outcome = await applyInput(store, dir, input, policy);
	// The compat-layer contract: the call completes and yields model-facing text.
	expect(typeof outcome.text, `${label}: outcome text`).toBe("string");
	expect(outcome.text.length, `${label}: model-facing text is non-empty`).toBeGreaterThan(0);
	expect(typeof outcome.isError).toBe("boolean");
	// Polarity must agree with the fixture's own expectation shape.
	if (caseData.expect?.error !== undefined) expect(outcome.isError, `${label}: fixture expects a rejection`).toBe(true);
	else expect(outcome.isError, `${label}: unexpected rejection: ${outcome.text}`).toBe(false);
}

/** One parity `apply` call: the call must complete, rejection or not. */
async function driveApplyCall(call: Record<string, any>, index: number, label: string): Promise<void> {
	const rel = displayRel(call.path ?? `fixture-${index}.ts`);
	const { dir, store } = makeCase(label);
	const abs = path.join(dir, rel);
	fs.mkdirSync(path.dirname(abs), { recursive: true });
	fs.writeFileSync(abs, String(call.text), "utf8");
	const tag = store.recordSnapshot(abs, String(call.text));

	const outcome = await applyInput(store, dir, `[${rel}#${tag}]\n${call.input}`);
	expect(typeof outcome.text, `${label}: outcome text`).toBe("string");
	expect(outcome.text.length, `${label}: model-facing text is non-empty`).toBeGreaterThan(0);
	expect(typeof outcome.isError).toBe("boolean");
	if (call.error !== undefined) expect(outcome.isError, `${label}: fixture expects a rejection`).toBe(true);
	else expect(outcome.isError, `${label}: unexpected rejection: ${outcome.text}`).toBe(false);
}

/** A call that needs a host-owned clipboard register seeded (no JS accessor). */
function hasClipboardSeed(call: Record<string, any>): boolean {
	return call.clipboard !== undefined && Object.keys(call.clipboard).length > 0;
}

describe("fixture corpus through the adapter", () => {
	const fixtureNames = fs
		.readdirSync(FIXTURE_DIR)
		.filter(name => name.endsWith(".json"))
		.sort();

	it("drives every payload-bearing case in the vendored corpus", async () => {
		expect(fixtureNames).toHaveLength(10);

		for (const fixture of fixtureNames) {
			const root = loadFixture(fixture);

			if (fixture === "patcher.json") {
				for (const [index, caseData] of (root.cases as Array<Record<string, any>>).entries()) {
					await drivePatcherCase(caseData, `patcher-${index}`);
					counts.patcherCases += 1;
				}
				continue;
			}

			for (const [caseIndex, caseData] of (root.cases as Array<Record<string, any>>).entries()) {
				const calls = (caseData.apply ?? []) as Array<Record<string, any>>;
				if (calls.length === 0) {
					// Parse-only (or name-only) case: the parse projection has no JS
					// API, so there is no compat-layer call to make for it.
					const reason =
						(caseData.parse ?? []).length > 0
							? "parse-axis only: asserts editCount/parser warnings, and the adapter exposes no parse projection (editInspect returns paths/entries/fileOps)"
							: "name-only case: no input/args/parse/apply payload to drive";
					counts.unreachable.push({ fixture, case: String(caseData.name), reason });
					continue;
				}
				for (const [index, call] of calls.entries()) {
					if (hasClipboardSeed(call)) {
						// The fixture seeds a host-owned register; `EditStore` exposes no
						// clipboard accessor, so this call cannot be replayed standalone.
						counts.unreachable.push({
							fixture,
							case: `${caseData.name} [apply#${index}]`,
							reason:
								"cross-call clipboard state: the fixture seeds a host-owned register, and EditStore exposes no clipboard accessor",
						});
						continue;
					}
					await driveApplyCall(call, index, `${fixture}-${caseIndex}`);
					counts.applyCalls += 1;
				}
			}
		}

		// The boundary is asserted, not assumed: 25 patcher cases + 201 drivable
		// apply calls (203 total minus the 2 host-owned clipboard seeds).
		expect(counts.patcherCases).toBe(25);
		expect(counts.applyCalls).toBe(201);
		expect(counts.unreachable).toHaveLength(101);
	});

	it("enumerates every unreachable case with its reason", () => {
		// Grouped so the boundary is reviewable at a glance rather than a bare count.
		const byFixture = new Map<string, { parse: number; nameOnly: number; clipboard: number }>();
		for (const entry of counts.unreachable) {
			const bucket = byFixture.get(entry.fixture) ?? { parse: 0, nameOnly: 0, clipboard: 0 };
			if (entry.reason.startsWith("cross-call clipboard")) bucket.clipboard += 1;
			else if (entry.reason.startsWith("parse-axis")) bucket.parse += 1;
			else bucket.nameOnly += 1;
			byFixture.set(entry.fixture, bucket);
		}
		const total = [...byFixture.values()].reduce((sum, b) => sum + b.parse + b.nameOnly + b.clipboard, 0);
		expect(total).toBe(counts.unreachable.length);
		expect(counts.unreachable.length + counts.applyCalls + counts.patcherCases).toBeGreaterThan(0);
		// Every entry must carry a non-empty reason; nothing is silently skipped.
		for (const entry of counts.unreachable) {
			expect(entry.reason.length, `${entry.fixture} / ${entry.case}`).toBeGreaterThan(20);
		}
		expect(counts.unreachable.filter(entry => entry.reason.startsWith("cross-call clipboard"))).toHaveLength(2);
		expect(counts.unreachable.filter(entry => entry.reason.startsWith("parse-axis"))).toHaveLength(96);
		expect(counts.unreachable.filter(entry => entry.reason.startsWith("name-only"))).toHaveLength(3);
	});
});
