/**
 * T2 (native hashline migration) wiring regression: drives the real DSH entry
 * point `executeHashlineSingle` end to end — policy → `EditSession` → writer →
 * DSH guards → session store — against the native Rust engine.
 *
 * Scope is deliberately the *adapter wiring*, not the engine's own behaviour
 * (the engine is covered by `src/tools/hashline/test/**`): the checks here are
 * the things typecheck cannot prove —
 *  - the payload reaches the engine and the bytes reach disk through DSH's
 *    `writethrough` channel,
 *  - the model-facing text and the `EditToolDetails` shape are preserved,
 *  - native rejections surface as `MismatchError` carrying the native text,
 *  - the no-op escalation fires on the 3rd identical payload,
 *  - the `EditStore` survives the DSH per-call `ToolSession` round trip, so a
 *    tag minted by one call validates in the next.
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { getDefault } from "../../src/tools/omp/config/settings-schema.ts";
import { Settings } from "../../src/tools/omp/config/settings.ts";
import type { ToolSession } from "../../src/tools/omp/sdk.ts";
import { canonicalSnapshotKey } from "../../src/tools/omp/edit/file-snapshot-store.ts";
import { executeHashlineSingle } from "../../src/tools/omp/edit/hashline/execute.ts";
import { MismatchError } from "../../src/tools/hashline/native/index.ts";
import { buildHashlineEditPolicy } from "../../src/tools/hashline/native/policy.ts";
import { attachOmpSessionState, persistOmpSessionState } from "../../src/tools/shared/session-state.ts";
import type { RuntimeConfig } from "../../src/config/settings.ts";

/**
 * Realpath'd cwd: DSH records snapshot keys through `canonicalSnapshotKey`
 * (which realpaths), while the engine resolves authored paths against
 * `policy.cwd`. Production reaches this through `process.cwd()`; a workspace
 * under `%TEMP%` comes back in Windows short form (`XIAOSO~1`), so the
 * fixture keeps the **raw** short-name path as the session cwd and relies on
 * `buildHashlineEditPolicy`'s `canonicalCwd` to normalize it — this spec
 * would fail on every case below if that normalization regressed.
 */
const rawCwd = fs.mkdtempSync(path.join(os.tmpdir(), "t2-native-"));
const cwd = fs.realpathSync.native(rawCwd);
const file = path.join(cwd, "demo.ts");
const ORIGINAL = "const a = 1;\nconst b = 2;\nconst c = 3;\n";

function makeSession(overrides: Partial<RuntimeConfig> = {}): ToolSession {
	const config = {
		editFuzzyMatch: true,
		editFuzzyThreshold: 0.95,
		editEnforceSeenLines: false,
		editBlockAutoGenerated: true,
		...overrides,
	} as unknown as RuntimeConfig;
	return {
		// The raw (possibly short-name) path, exactly as DSH hands it over.
		cwd: rawCwd,
		settings: new Settings(config, getDefault),
	} as unknown as ToolSession;
}

/** DSH's sandbox-routed write channel, reduced to the file effect under test. */
const writes: string[] = [];
async function writethrough(dst: string, content: string): Promise<void> {
	writes.push(dst);
	await fs.promises.writeFile(dst, content, "utf8");
}

function edit(session: ToolSession, input: string) {
	return executeHashlineSingle({ session, input, writethrough });
}

function tagOf(text: string): string {
	const match = /^\[[^\]#]+#([0-9A-F]{4})\]/m.exec(text);
	if (!match) throw new Error(`no hashline header in ${JSON.stringify(text)}`);
	return match[1];
}

beforeAll(() => {
	fs.writeFileSync(file, ORIGINAL);
});

afterAll(() => {
	fs.rmSync(rawCwd, { recursive: true, force: true });
});

describe("native hashline wiring (T2)", () => {
	it("canonicalizes the policy cwd (Windows short names)", () => {
		const policy = buildHashlineEditPolicy(makeSession());
		expect(policy.cwd).toBe(cwd);
		expect(policy.mode).toBe("hashline");
		expect(policy.rawInput).toBe(false);
		if (rawCwd !== cwd) expect(policy.cwd).not.toBe(rawCwd);
	});

	it("recovers a bare authored path onto the tag's snapshot file", async () => {
		// `nested/a.ts` exists; a bare `a.ts` does not. The engine's tag path
		// recovery must rebind the authored name onto the file the snapshot tag
		// uniquely names — which only works when `policy.cwd` is canonical
		// (byte-wise `is_within` against the engine's canonical snapshot key).
		const nested = path.join(cwd, "nested");
		fs.mkdirSync(nested, { recursive: true });
		const nestedFile = path.join(nested, "a.ts");
		const body = "export const a = 1;\n";
		fs.writeFileSync(nestedFile, body);
		const session = makeSession();
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");
		const tag = getFileSnapshotStore(session).recordSnapshotFile(canonicalSnapshotKey(nestedFile), [1]);

		const result = await edit(session, `[a.ts#${tag}]\nPUT 1-1:\n+export const a = 9;`);
		expect(result.details?.path).toBe(nestedFile);
		expect(fs.readFileSync(nestedFile, "utf8")).toBe("export const a = 9;\n");
	});

	it("applies an update through writethrough and reports the DSH detail shape", async () => {
		fs.writeFileSync(file, ORIGINAL);
		const session = makeSession();

		// Mint the tag the way `read` does.
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");
		const minted = getFileSnapshotStore(session).recordSnapshotFile(canonicalSnapshotKey(file), [1, 2, 3]);

		const result = await edit(session, `[demo.ts#${minted}]\nPUT 1-1:\n+const a = 9;`);

		expect(fs.readFileSync(file, "utf8")).toBe("const a = 9;\nconst b = 2;\nconst c = 3;\n");
		expect(writes.at(-1)).toBe(file);
		expect(result.isError).toBeUndefined();
		const text = result.content.map(part => (part.type === "text" ? part.text : "")).join("");
		expect(text.startsWith(`[demo.ts#${tagOf(text)}]`)).toBe(true);
		expect(text).toContain("1:const a = 9;");
		expect(result.details?.op).toBe("update");
		expect(result.details?.path).toBe(file);
		expect(result.details?.diff).toContain("+1|const a = 9;");
		expect(result.details?.oldText).toBe(ORIGINAL);
		expect(result.details?.newText).toBe("const a = 9;\nconst b = 2;\nconst c = 3;\n");
	});

	it("raises MismatchError with the native teaching text for a bogus tag", async () => {
		fs.writeFileSync(file, ORIGINAL);
		const session = makeSession();
		const before = writes.length;
		await expect(edit(session, "[demo.ts#0000]\nPUT 1-1:\n+const a = 9;")).rejects.toBeInstanceOf(MismatchError);
		await expect(edit(session, "[demo.ts#0000]\nPUT 1-1:\n+const a = 9;")).rejects.toThrow(
			/hash #0000 is not from this session/,
		);
		expect(writes.length).toBe(before);
		expect(fs.readFileSync(file, "utf8")).toBe(ORIGINAL);
	});

	it("surfaces the byte-identical no-op hint twice, then escalates on the third", async () => {
		fs.writeFileSync(file, ORIGINAL);
		const session = makeSession();
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");
		const minted = getFileSnapshotStore(session).recordSnapshotFile(canonicalSnapshotKey(file), [1, 2, 3]);
		const input = `[demo.ts#${minted}]\nPUT 2-2:\n+const b = 2;`;

		for (const pass of [1, 2]) {
			const result = await edit(session, input);
			const text = result.content.map(part => (part.type === "text" ? part.text : "")).join("");
			expect(text).toContain("produced no change");
			expect(text).not.toContain("STOP.");
			expect(result.details?.diff).toBe("");
			// Native has no `noop` op: a no-op is `update` with zero bytes written,
			// and DSH must not synthesize the old engine's fourth state.
			expect(result.details?.op).toBe("update");
			void pass;
		}

		await expect(edit(session, input)).rejects.toThrow(/STOP\. Edits to demo\.ts have been a byte-identical no-op 3 times/);
	});

	it("shapes a multi-file patch into perFileResults", async () => {
		const other = path.join(cwd, "other.ts");
		const otherBody = "export const o = 1;\n";
		fs.writeFileSync(file, ORIGINAL);
		fs.writeFileSync(other, otherBody);
		const session = makeSession();
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");
		const store = getFileSnapshotStore(session);
		const tagA = store.recordSnapshotFile(canonicalSnapshotKey(file), [1, 2, 3]);
		const tagB = store.recordSnapshotFile(canonicalSnapshotKey(other), [1]);

		const result = await edit(
			session,
			`[demo.ts#${tagA}]\nPUT 1-1:\n+const a = 9;\n[other.ts#${tagB}]\nPUT 1-1:\n+export const o = 2;`,
		);

		expect(fs.readFileSync(file, "utf8")).toBe("const a = 9;\nconst b = 2;\nconst c = 3;\n");
		expect(fs.readFileSync(other, "utf8")).toBe("export const o = 2;\n");
		const text = result.content.map(part => (part.type === "text" ? part.text : "")).join("");
		// Native joins the per-file texts with a blank line; DSH passes it through.
		expect(text).toContain("\n\n");
		expect(result.details?.perFileResults).toHaveLength(2);
		expect(result.details?.perFileResults?.map(entry => entry.path)).toEqual([file, other]);
		expect(result.details?.perFileResults?.every(entry => entry.op === "update" && entry.diff.length > 0)).toBe(true);
	});

	it("deletes through the writer", async () => {
		fs.writeFileSync(file, ORIGINAL);
		const session = makeSession();
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");
		const minted = getFileSnapshotStore(session).recordSnapshotFile(canonicalSnapshotKey(file), [1, 2, 3]);

		const result = await edit(session, `[demo.ts#${minted}]\nREM`);
		expect(fs.existsSync(file)).toBe(false);
		expect(result.details?.op).toBe("delete");
		const text = result.content.map(part => (part.type === "text" ? part.text : "")).join("");
		expect(text).toBe("Deleted demo.ts");
	});

	it("moves through the writer and keeps source/dest metadata", async () => {
		fs.writeFileSync(file, ORIGINAL);
		const dest = path.join(cwd, "moved.ts");
		fs.rmSync(dest, { force: true });
		const session = makeSession();
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");
		const minted = getFileSnapshotStore(session).recordSnapshotFile(canonicalSnapshotKey(file), [1, 2, 3]);

		const result = await edit(session, `[demo.ts#${minted}]\nMV moved.ts`);
		expect(fs.existsSync(file)).toBe(false);
		expect(fs.readFileSync(dest, "utf8")).toBe(ORIGINAL);
		expect(result.details?.move).toBe(dest);
		expect(result.details?.path).toBe(dest);
		expect(result.details?.sourcePath).toBe("demo.ts");
	});

	it("refuses an auto-generated file through the engine guard", async () => {
		const generated = path.join(cwd, "gen.ts");
		const body = "// @generated by tool\nconst x = 1;\n";
		fs.writeFileSync(generated, body);
		const session = makeSession();
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");
		const minted = getFileSnapshotStore(session).recordSnapshotFile(canonicalSnapshotKey(generated), [1, 2]);

		await expect(edit(session, `[gen.ts#${minted}]\nPUT 2-2:\n+const x = 2;`)).rejects.toThrow(
			/Cannot modify auto-generated file: gen\.ts/,
		);
		expect(fs.readFileSync(generated, "utf8")).toBe(body);
	});

	it("carries a writer refusal back as the model-facing error", async () => {
		fs.writeFileSync(file, ORIGINAL);
		const session = makeSession();
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");
		const minted = getFileSnapshotStore(session).recordSnapshotFile(canonicalSnapshotKey(file), [1, 2, 3]);

		await expect(
			executeHashlineSingle({
				session,
				input: `[demo.ts#${minted}]\nPUT 1-1:\n+const a = 9;`,
				writethrough: async () => {
					throw new Error("sandbox denied the write");
				},
			}),
		).rejects.toThrow(/sandbox denied the write/);
		expect(fs.readFileSync(file, "utf8")).toBe(ORIGINAL);
	});

	it("keeps one store across DSH per-call ToolSession instances", async () => {
		fs.writeFileSync(file, ORIGINAL);
		const sessionKey = {};
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");

		// Call 1 (read-like): mint a tag, then hand the store back to the DSH session.
		const first = makeSession();
		const minted = getFileSnapshotStore(first).recordSnapshotFile(canonicalSnapshotKey(file), [1, 2, 3]);
		persistOmpSessionState(sessionKey, first);

		// Call 2 (edit): a *new* ToolSession re-attaches the same store, so the
		// tag minted in call 1 still validates.
		const second = makeSession();
		attachOmpSessionState(second, sessionKey);
		expect(getFileSnapshotStore(second)).toBe(getFileSnapshotStore(first));

		const result = await edit(second, `[demo.ts#${minted}]\nPUT 3-3:\n+const c = 9;`);
		expect(result.details?.op).toBe("update");
		expect(fs.readFileSync(file, "utf8")).toBe("const a = 1;\nconst b = 2;\nconst c = 9;\n");
	});

	it("honors the enforceSeenLines setting", async () => {
		fs.writeFileSync(file, ORIGINAL);
		const session = makeSession({ editEnforceSeenLines: true });
		const { getFileSnapshotStore } = await import("../../src/tools/omp/edit/file-snapshot-store.ts");
		// Only lines 1-2 were displayed.
		getFileSnapshotStore(session).recordSnapshotFile(canonicalSnapshotKey(file), [1, 2]);

		await expect(edit(session, `[demo.ts#${await hash(file)}]\nPUT 3-3:\n+const c = 9;`)).rejects.toThrow(
			/never displayed/,
		);
		expect(fs.readFileSync(file, "utf8")).toBe(ORIGINAL);
	});
});

/** Content tag for `absolutePath`'s current bytes (whole-file snapshot hash). */
async function hash(absolutePath: string): Promise<string> {
	const { computeFileHash } = await import("../../src/tools/hashline/native/index.ts");
	const { normalizeToLF } = await import("../../src/tools/omp/edit/normalize.ts");
	return computeFileHash(normalizeToLF(await fs.promises.readFile(absolutePath, "utf8")));
}
