/**
 * Production writer branch coverage for the native hashline engine.
 *
 * `src/tools/hashline/native/writer.ts` is the callback the Rust engine calls
 * for every landed change. The 12 migrated hashline suites drive the engine
 * through `hashline/test/harness.ts`, which brings **its own** writer, so a
 * regression inside this file (e.g. a `move` that forgets to delete the
 * source) cannot turn them red. `native-edit-wiring.spec.ts` covers the
 * branches end to end; this file pins them at the unit level so each branch,
 * guard and error path is asserted directly.
 *
 * Contract under test (writer.ts):
 *  - `delete` → `fs.rm`, `{written: ""}`, no channel call
 *  - `move`   → guard on the destination, channel-write the destination
 *               verbatim, then delete the source (dest first on purpose)
 *  - `create`/`update` → guard, channel-write verbatim, report what landed
 *  - malformed requests → `ToolError`; channel failures propagate untouched
 *  - the leading `error` argument is the preview channel's, never a request
 *
 * "Verbatim" is the whole point: `EditWriteRequest.content` is the engine's
 * final byte sequence, notebook JSON included. The host must not re-serialize
 * it — the old TS engine handed over editable cell text instead, and running
 * the native engine's JSON back through that serializer made every `.ipynb`
 * edit throw `Invalid notebook editable representation`.
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { getDefault } from "../../src/tools/omp/config/settings-schema.ts";
import { Settings } from "../../src/tools/omp/config/settings.ts";
import type { NotebookDocument } from "../../src/tools/omp/edit/notebook.ts";
import type { ToolSession } from "../../src/tools/omp/sdk.ts";
import { createHashlineWriter } from "../../src/tools/hashline/native/writer.ts";
import type { EditWriteRequest } from "../../src/tools/hashline/native/index.ts";
import type { RuntimeConfig } from "../../src/config/settings.ts";

const rawCwd = fs.mkdtempSync(path.join(os.tmpdir(), "t2-writer-"));
const cwd = fs.realpathSync.native(rawCwd);
const TS_FILE = path.join(cwd, "demo.ts");
const BODY = "const a = 1;\nconst b = 2;\n";

function makeSession(): ToolSession {
	const config = {
		editFuzzyMatch: true,
		editFuzzyThreshold: 0.95,
		editEnforceSeenLines: false,
		editBlockAutoGenerated: true,
	} as unknown as RuntimeConfig;
	return { cwd: rawCwd, settings: new Settings(config, getDefault) } as unknown as ToolSession;
}

interface ChannelCall {
	dst: string;
	content: string;
	signal: unknown;
	file: unknown;
}

/** DSH's sandbox-routed channel, reduced to its observable effect. */
function makeChannel(options: { failOn?: (dst: string) => Error } = {}) {
	const calls: ChannelCall[] = [];
	const writethrough = async (dst: string, content: string, signal?: unknown, file?: unknown): Promise<void> => {
		const failure = options.failOn?.(dst);
		if (failure) throw failure;
		calls.push({ dst, content, signal, file });
		await fs.promises.writeFile(dst, content, "utf8");
	};
	return { calls, writethrough };
}

function request(overrides: Partial<EditWriteRequest>): EditWriteRequest {
	return {
		path: TS_FILE,
		displayPath: "demo.ts",
		op: "update",
		flushLsp: false,
		...overrides,
	} as EditWriteRequest;
}

function write(session: ToolSession, channel: ReturnType<typeof makeChannel>["writethrough"], signal?: AbortSignal) {
	return createHashlineWriter({ session, writethrough: channel, signal });
}

beforeAll(() => {
	fs.writeFileSync(TS_FILE, BODY);
});

afterAll(() => {
	fs.rmSync(rawCwd, { recursive: true, force: true });
});

describe("native hashline writer branches", () => {
	it("update: writes through the channel and reports what landed", async () => {
		const { calls, writethrough } = makeChannel();
		const response = await write(makeSession(), writethrough)(null, request({ op: "update", content: "const a = 9;\n" }));
		expect(calls).toHaveLength(1);
		expect(calls[0].dst).toBe(TS_FILE);
		expect(calls[0].content).toBe("const a = 9;\n");
		expect(response).toEqual({ written: "const a = 9;\n" });
		expect(fs.readFileSync(TS_FILE, "utf8")).toBe("const a = 9;\n");
	});

	it("create: writes a file that does not exist yet", async () => {
		const target = path.join(cwd, "fresh.ts");
		const { calls, writethrough } = makeChannel();
		const response = await write(makeSession(), writethrough)(
			null,
			request({ op: "create", path: target, displayPath: "fresh.ts", content: "export const fresh = true;\n" }),
		);
		expect(calls.map(call => call.dst)).toEqual([target]);
		expect(response.written).toBe("export const fresh = true;\n");
		expect(fs.readFileSync(target, "utf8")).toBe("export const fresh = true;\n");
	});

	it("delete: removes the file and never touches the write channel", async () => {
		const target = path.join(cwd, "gone.ts");
		fs.writeFileSync(target, BODY);
		const { calls, writethrough } = makeChannel();
		const response = await write(makeSession(), writethrough)(
			null,
			request({ op: "delete", path: target, displayPath: "gone.ts" }),
		);
		expect(response).toEqual({ written: "" });
		expect(calls).toHaveLength(0);
		expect(fs.existsSync(target)).toBe(false);
	});

	it("move: writes the destination first, then deletes the source", async () => {
		const source = path.join(cwd, "move-src.ts");
		const dest = path.join(cwd, "move-dest.ts");
		fs.writeFileSync(source, BODY);
		fs.rmSync(dest, { force: true });
		const { calls, writethrough } = makeChannel();
		const response = await write(makeSession(), writethrough)(
			null,
			request({ op: "move", path: source, displayPath: "move-src.ts", moveTo: dest, content: "const moved = 1;\n" }),
		);
		expect(calls.map(call => call.dst)).toEqual([dest]);
		expect(response.written).toBe("const moved = 1;\n");
		expect(fs.readFileSync(dest, "utf8")).toBe("const moved = 1;\n");
		expect(fs.existsSync(source)).toBe(false);
	});

	it("move without a destination is a ToolError", async () => {
		const { calls, writethrough } = makeChannel();
		await expect(write(makeSession(), writethrough)(null, request({ op: "move", content: "x\n" }))).rejects.toThrow(
			/Native edit move request omitted destination/,
		);
		expect(calls).toHaveLength(0);
	});

	it("a non-delete request without content is a ToolError", async () => {
		const { calls, writethrough } = makeChannel();
		await expect(write(makeSession(), writethrough)(null, request({ op: "update" }))).rejects.toThrow(
			/Native edit update request omitted content/,
		);
		expect(calls).toHaveLength(0);
	});

	it("refuses an auto-generated file before the channel is called", async () => {
		const generated = path.join(cwd, "generated.ts");
		fs.writeFileSync(generated, "// @generated by tool\nconst x = 1;\n");
		const { calls, writethrough } = makeChannel();
		await expect(
			write(makeSession(), writethrough)(
				null,
				request({ op: "update", path: generated, displayPath: "generated.ts", content: "// @generated by tool\nconst x = 2;\n" }),
			),
		).rejects.toThrow();
		expect(calls).toHaveLength(0);
		expect(fs.readFileSync(generated, "utf8")).toBe("// @generated by tool\nconst x = 1;\n");
	});

	it("refuses an auto-generated move destination and keeps the source intact", async () => {
		const source = path.join(cwd, "keep-src.ts");
		const dest = path.join(cwd, "generated-dest.ts");
		fs.writeFileSync(source, BODY);
		fs.writeFileSync(dest, "// @generated by tool\nconst y = 1;\n");
		const { calls, writethrough } = makeChannel();
		await expect(
			write(makeSession(), writethrough)(
				null,
				request({ op: "move", path: source, displayPath: "keep-src.ts", moveTo: dest, content: "const y = 2;\n" }),
			),
		).rejects.toThrow();
		expect(calls).toHaveLength(0);
		expect(fs.existsSync(source)).toBe(true);
		expect(fs.readFileSync(dest, "utf8")).toBe("// @generated by tool\nconst y = 1;\n");
	});

	it("lands the engine's final bytes verbatim, including notebook JSON", async () => {
		const nbFile = path.join(cwd, "nb.ipynb");
		const notebook: NotebookDocument = {
			cells: [{ cell_type: "code", source: ["print(2)\n"], metadata: {}, execution_count: null }],
			metadata: {},
			nbformat: 4,
			nbformat_minor: 5,
		};
		// What the engine sends: it already serialized the edited cell
		// projection back to nbformat JSON (`crates/pi-edit/src/files.rs::persist`).
		const engineJson = JSON.stringify(notebook, null, 1);
		fs.writeFileSync(nbFile, JSON.stringify(notebook, null, 1));
		const { calls, writethrough } = makeChannel();
		const response = await write(makeSession(), writethrough)(
			null,
			request({ op: "update", path: nbFile, displayPath: "nb.ipynb", content: engineJson }),
		);
		expect(calls).toHaveLength(1);
		// The channel receives exactly what the engine handed over — the writer
		// must not re-serialize. Running notebook JSON back through the cell-text
		// serializer is the historical bug this pins against: it throws
		// `Invalid notebook editable representation`, so every `.ipynb` edit failed.
		expect(calls[0].content).toBe(engineJson);
		expect(JSON.parse(calls[0].content).cells).toHaveLength(1);
		// …and the response reports the bytes that actually landed.
		expect(response.written).toBe(engineJson);
		expect(JSON.parse(fs.readFileSync(nbFile, "utf8")).cells[0].cell_type).toBe("code");
	});

	it("does not reinterpret a notebook payload that is already JSON", async () => {
		// Guard against reintroducing host-side notebook serialization: a payload
		// that is *not* valid notebook JSON must still be written verbatim (the
		// engine owns the format), not rejected by a host-side parser.
		const nbFile = path.join(cwd, "opaque.ipynb");
		fs.writeFileSync(nbFile, "{\n \"cells\": []\n}");
		const { calls, writethrough } = makeChannel();
		const opaque = "# %% [code] cell:0\nprint(1)\n";
		const response = await write(makeSession(), writethrough)(
			null,
			request({ op: "update", path: nbFile, displayPath: "opaque.ipynb", content: opaque }),
		);
		expect(calls[0].content).toBe(opaque);
		expect(response.written).toBe(opaque);
		expect(fs.readFileSync(nbFile, "utf8")).toBe(opaque);
	});

	it("lands the engine's notebook JSON verbatim on a create too", async () => {
		const target = path.join(cwd, "fresh.ipynb");
		fs.rmSync(target, { force: true });
		// The engine serializes a brand-new notebook itself (`files.rs::persist_new`)
		// before the host ever sees it.
		const engineJson = JSON.stringify(
			{ cells: [{ cell_type: "code", source: ["answer = 42"] }], metadata: {}, nbformat: 4, nbformat_minor: 5 },
			null,
			1,
		);
		const { calls, writethrough } = makeChannel();
		const response = await write(makeSession(), writethrough)(
			null,
			request({ op: "create", path: target, displayPath: "fresh.ipynb", content: engineJson }),
		);
		expect(calls).toHaveLength(1);
		expect(calls[0].content).toBe(engineJson);
		expect(response.written).toBe(engineJson);
		expect(JSON.parse(fs.readFileSync(target, "utf8")).nbformat).toBe(4);
	});

	it("lands the engine's notebook JSON verbatim on a move too", async () => {
		const source = path.join(cwd, "mv-src.ipynb");
		const dest = path.join(cwd, "mv-dest.ipynb");
		const notebook: NotebookDocument = {
			cells: [{ cell_type: "markdown", source: ["# T\n"], metadata: {} }],
			metadata: {},
			nbformat: 4,
			nbformat_minor: 5,
		};
		const engineJson = JSON.stringify(notebook, null, 1);
		fs.writeFileSync(source, engineJson);
		fs.rmSync(dest, { force: true });
		const { calls, writethrough } = makeChannel();
		const response = await write(makeSession(), writethrough)(
			null,
			request({ op: "move", path: source, displayPath: "mv-src.ipynb", moveTo: dest, content: engineJson }),
		);
		expect(calls).toHaveLength(1);
		expect(calls[0].dst).toBe(dest);
		expect(calls[0].content).toBe(engineJson);
		expect(response.written).toBe(engineJson);
		expect(fs.existsSync(source)).toBe(false);
		expect(JSON.parse(fs.readFileSync(dest, "utf8")).cells[0].source).toEqual(["# T\n"]);
	});

	it("propagates a channel failure and leaves the file untouched", async () => {
		const target = path.join(cwd, "refused.ts");
		fs.writeFileSync(target, BODY);
		const boom = new Error("blocked write: refused.ts");
		const { calls, writethrough } = makeChannel({ failOn: dst => (dst === target ? boom : undefined as never) });
		await expect(
			write(makeSession(), writethrough)(null, request({ op: "update", path: target, displayPath: "refused.ts", content: "x\n" })),
		).rejects.toThrow(/blocked write: refused\.ts/);
		expect(calls).toHaveLength(0);
		expect(fs.readFileSync(target, "utf8")).toBe(BODY);
	});

	it("ignores the leading error argument (preview channel, not a write request)", async () => {
		const { calls, writethrough } = makeChannel();
		const response = await write(makeSession(), writethrough)(
			new Error("preview-side error"),
			request({ op: "update", content: "const a = 3;\n" }),
		);
		expect(calls).toHaveLength(1);
		expect(response.written).toBe("const a = 3;\n");
	});

	it("forwards the caller's AbortSignal to the channel", async () => {
		const controller = new AbortController();
		const { calls, writethrough } = makeChannel();
		await write(makeSession(), writethrough, controller.signal)(
			null,
			request({ op: "update", content: "const a = 4;\n" }),
		);
		expect(calls[0].signal).toBe(controller.signal);
	});
});
