/**
 * Partial-write regression: a multi-section payload that lands section #1 and
 * is then refused by the host write channel must tell the model *which*
 * sections are already on disk.
 *
 * The old TS engine wrapped a mid-batch commit failure as
 * `Failed to write <path>: <message> Sections already written: a.ts.` from its
 * prepared batch (`engine/patcher.ts:287-296` at v17.3.5). The native engine
 * applies one file at a time, aborts on the first writer throw, and reports
 * only the callback's own message with an empty `files` list — so without the
 * adapter's re-attachment the model sees `sandbox denied the write` and has no
 * way to know that `a.ts` was already modified (it would re-issue the whole
 * patch and double-apply it).
 *
 * Pinned contract:
 *  - `createHashlineWriter(...).landedPaths` records only writes that actually
 *    landed, in write order, in authored display form (for a move: the source);
 *  - `executeHashlineSingle` appends ` Sections already written: <a, b>.` to
 *    the rejection exactly when at least one section landed;
 *  - a rejection with nothing landed (single file, first file, bad tag) stays
 *    byte-identical to the engine's own text.
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { getDefault } from "../../src/tools/omp/config/settings-schema.ts";
import { Settings } from "../../src/tools/omp/config/settings.ts";
import { canonicalSnapshotKey } from "../../src/tools/omp/edit/file-snapshot-store.ts";
import { getFileSnapshotStore } from "../../src/tools/omp/edit/file-snapshot-store.ts";
import { executeHashlineSingle } from "../../src/tools/omp/edit/hashline/execute.ts";
import type { ToolSession } from "../../src/tools/omp/sdk.ts";
import { MismatchError, type EditWriteRequest } from "../../src/tools/hashline/native/index.ts";
import { createHashlineWriter } from "../../src/tools/hashline/native/writer.ts";
import type { WritethroughCallback } from "../../src/tools/omp/tools/writethrough.ts";
import type { RuntimeConfig } from "../../src/config/settings.ts";

const rawCwd = fs.mkdtempSync(path.join(os.tmpdir(), "t2-partial-"));
const cwd = fs.realpathSync.native(rawCwd);

function makeSession(): ToolSession {
	const config = {
		editFuzzyMatch: true,
		editFuzzyThreshold: 0.95,
		editEnforceSeenLines: false,
		editBlockAutoGenerated: true,
	} as unknown as RuntimeConfig;
	return { cwd: rawCwd, settings: new Settings(config, getDefault) } as unknown as ToolSession;
}

/** DSH's sandbox-routed channel, with optional refusal for chosen targets. */
function makeChannel(refuse?: (dst: string) => string | undefined) {
	const landed: string[] = [];
	const writethrough: WritethroughCallback = async (dst, content) => {
		const failure = refuse?.(dst);
		if (failure !== undefined) throw new Error(failure);
		// The real channel creates missing parent directories (see
		// `writethroughNoop`); a move into a fresh subdirectory depends on it.
		await fs.promises.mkdir(path.dirname(dst), { recursive: true });
		await fs.promises.writeFile(dst, content, "utf8");
		landed.push(dst);
	};
	return { writethrough, landed };
}

/** Refuse every write to `dst`. */
function refuseOn(dst: string, message = "sandbox denied the write") {
	return (target: string): string | undefined => (target === dst ? message : undefined);
}

const abs = (name: string): string => path.join(cwd, name);

function put(name: string, body: string): string {
	const target = abs(name);
	fs.writeFileSync(target, body, "utf8");
	return target;
}

/** Mint tags the way `read` does, then author a `PUT 1-1:` payload. */
function patch(session: ToolSession, files: Array<[name: string, replacement: string]>): string {
	const store = getFileSnapshotStore(session);
	return files
		.map(([name, replacement]) => {
			const tag = store.recordSnapshotFile(canonicalSnapshotKey(abs(name)), [1]);
			return `[${name}#${tag}]\nPUT 1-1:\n+${replacement}`;
		})
		.join("\n");
}

/** The rejection `executeHashlineSingle` raises, asserted to be the DSH error type. */
async function rejection(promise: Promise<unknown>): Promise<MismatchError> {
	try {
		await promise;
	} catch (error) {
		expect(error).toBeInstanceOf(MismatchError);
		return error as MismatchError;
	}
	throw new Error("expected the payload to be rejected, but it applied");
}

function textOf(result: { content: Array<{ type: string; text?: string }> }): string {
	return result.content.map(part => (part.type === "text" ? (part.text ?? "") : "")).join("");
}

const A = "a.ts";
const B = "b.ts";
const C = "c.ts";

beforeAll(() => {
	// Files are (re)created per case; nothing global to set up beyond the dir.
});

afterAll(() => {
	fs.rmSync(rawCwd, { recursive: true, force: true });
});

describe("partial-write breadcrumb (native hashline)", () => {
	it("appends the landed section when the second file is refused", async () => {
		const a = put(A, "A1\nA2\n");
		const b = put(B, "B1\nB2\n");
		const session = makeSession();
		const { writethrough, landed } = makeChannel(refuseOn(b));

		const error = await rejection(
			executeHashlineSingle({
				session,
				input: patch(session, [
					[A, "AAA"],
					[B, "BBB"],
				]),
				writethrough,
			}),
		);

		// Native's own message survives, and the breadcrumb names section #1.
		expect(error.message).toContain("sandbox denied the write");
		expect(error.message.endsWith("Sections already written: a.ts.")).toBe(true);
		// The DSH renderer reads `displayMessage`; it must carry the same text.
		expect(error.displayMessage).toBe(error.message);
		// And the claim is true on disk: a.ts landed, b.ts did not.
		expect(fs.readFileSync(a, "utf8")).toBe("AAA\nA2\n");
		expect(fs.readFileSync(b, "utf8")).toBe("B1\nB2\n");
		expect(landed).toEqual([a]);
	});

	it("lists every landed section in write order when the third file is refused", async () => {
		const a = put(A, "A1\nA2\n");
		const b = put(B, "B1\nB2\n");
		const c = put(C, "C1\nC2\n");
		const session = makeSession();
		const { writethrough } = makeChannel(refuseOn(c));

		const error = await rejection(
			executeHashlineSingle({
				session,
				input: patch(session, [
					[A, "AAA"],
					[B, "BBB"],
					[C, "CCC"],
				]),
				writethrough,
			}),
		);

		expect(error.message.endsWith("Sections already written: a.ts, b.ts.")).toBe(true);
		expect(fs.readFileSync(a, "utf8")).toBe("AAA\nA2\n");
		expect(fs.readFileSync(b, "utf8")).toBe("BBB\nB2\n");
		expect(fs.readFileSync(c, "utf8")).toBe("C1\nC2\n");
	});

	it("stays byte-identical when the first file is refused", async () => {
		const a = put(A, "A1\nA2\n");
		const b = put(B, "B1\nB2\n");
		const session = makeSession();
		const { writethrough, landed } = makeChannel(refuseOn(a));

		const error = await rejection(
			executeHashlineSingle({
				session,
				input: patch(session, [
					[A, "AAA"],
					[B, "BBB"],
				]),
				writethrough,
			}),
		);

		// Nothing landed, so the model must not be told anything was written.
		expect(error.message).toBe("sandbox denied the write");
		expect(error.message).not.toContain("already written");
		expect(landed).toEqual([]);
		expect(fs.readFileSync(a, "utf8")).toBe("A1\nA2\n");
		expect(fs.readFileSync(b, "utf8")).toBe("B1\nB2\n");
	});

	it("stays byte-identical for a single-file refusal", async () => {
		const a = put(A, "A1\nA2\n");
		const session = makeSession();
		const { writethrough } = makeChannel(refuseOn(a));

		const error = await rejection(
			executeHashlineSingle({
				session,
				input: patch(session, [[A, "AAA"]]),
				writethrough,
			}),
		);

		expect(error.message).toBe("sandbox denied the write");
		expect(fs.readFileSync(a, "utf8")).toBe("A1\nA2\n");
	});

	it("stays byte-identical when the payload is rejected before any write (bad tag)", async () => {
		const a = put(A, "A1\nA2\n");
		const session = makeSession();
		const { writethrough, landed } = makeChannel();

		const error = await rejection(
			executeHashlineSingle({
				session,
				input: `[${A}#0000]\nPUT 1-1:\n+AAA`,
				writethrough,
			}),
		);

		expect(error.message).toContain("is not from this session");
		expect(error.message).not.toContain("already written");
		expect(landed).toEqual([]);
		expect(fs.readFileSync(a, "utf8")).toBe("A1\nA2\n");
	});

	it("names a deleted section that landed before the refusal", async () => {
		const del = put("del.ts", "D1\n");
		const b = put(B, "B1\nB2\n");
		const session = makeSession();
		const store = getFileSnapshotStore(session);
		const delTag = store.recordSnapshotFile(canonicalSnapshotKey(del), [1]);
		const bTag = store.recordSnapshotFile(canonicalSnapshotKey(b), [1]);
		const { writethrough } = makeChannel(refuseOn(b));

		const error = await rejection(
			executeHashlineSingle({
				session,
				input: `[del.ts#${delTag}]\nREM\n[${B}#${bTag}]\nPUT 1-1:\n+BBB`,
				writethrough,
			}),
		);

		expect(error.message.endsWith("Sections already written: del.ts.")).toBe(true);
		expect(fs.existsSync(del)).toBe(false);
		expect(fs.readFileSync(b, "utf8")).toBe("B1\nB2\n");
	});

	it("names the moved source that landed before the refusal", async () => {
		const src = put("src.ts", "S1\nS2\n");
		const dest = abs("moved/dest.ts");
		const b = put(B, "B1\nB2\n");
		const session = makeSession();
		const store = getFileSnapshotStore(session);
		const srcTag = store.recordSnapshotFile(canonicalSnapshotKey(src), [1]);
		const bTag = store.recordSnapshotFile(canonicalSnapshotKey(b), [1]);
		const { writethrough } = makeChannel(refuseOn(b));

		const error = await rejection(
			executeHashlineSingle({
				session,
				input: `[src.ts#${srcTag}]\nMV moved/dest.ts\n[${B}#${bTag}]\nPUT 1-1:\n+BBB`,
				writethrough,
			}),
		);

		// The moved *source* is the section that landed (old engine semantics).
		expect(error.message.endsWith("Sections already written: src.ts.")).toBe(true);
		expect(fs.existsSync(src)).toBe(false);
		expect(fs.readFileSync(dest, "utf8")).toBe("S1\nS2\n");
		expect(fs.readFileSync(b, "utf8")).toBe("B1\nB2\n");
	});

	it("leaves the success path untouched", async () => {
		const a = put(A, "A1\nA2\n");
		const b = put(B, "B1\nB2\n");
		const session = makeSession();
		const { writethrough, landed } = makeChannel();

		const result = await executeHashlineSingle({
			session,
			input: patch(session, [
				[A, "AAA"],
				[B, "BBB"],
			]),
			writethrough,
		});

		expect(textOf(result)).not.toContain("already written");
		expect(fs.readFileSync(a, "utf8")).toBe("AAA\nA2\n");
		expect(fs.readFileSync(b, "utf8")).toBe("BBB\nB2\n");
		expect(landed).toEqual([a, b]);
	});

	it("records only successful writes in landedPaths", async () => {
		const one = put("one.ts", "ONE\n");
		const two = put("two.ts", "TWO\n");
		const session = makeSession();

		// Happy path: both writes land, in order.
		const ok = makeChannel();
		const writer = createHashlineWriter({ session, writethrough: ok.writethrough });
		expect(writer.landedPaths).toEqual([]);
		await writer(null, {
			op: "update",
			path: one,
			displayPath: "one.ts",
			content: "ONE!\n",
		} as EditWriteRequest);
		await writer(null, {
			op: "update",
			path: two,
			displayPath: "two.ts",
			content: "TWO!\n",
		} as EditWriteRequest);
		expect(writer.landedPaths).toEqual(["one.ts", "two.ts"]);

		// Refusal path: the failing write is not recorded, the earlier one is.
		const bad = makeChannel(refuseOn(two));
		const failing = createHashlineWriter({ session, writethrough: bad.writethrough });
		await failing(null, {
			op: "update",
			path: one,
			displayPath: "one.ts",
			content: "ONE?\n",
		} as EditWriteRequest);
		await expect(
			failing(null, {
				op: "update",
				path: two,
				displayPath: "two.ts",
				content: "TWO?\n",
			} as EditWriteRequest),
		).rejects.toThrow("sandbox denied the write");
		expect(failing.landedPaths).toEqual(["one.ts"]);
	});
});
