/**
 * Notebook (`.ipynb`) hashline round trip — read tag → edit → bytes → second edit.
 *
 * Written to settle one specific claim: that "every hashline edit to a `.ipynb`
 * fails with `Edit rejected for nb.ipynb: file changed between read and edit`,
 * because DSH renders cell markers 1-based while the native engine renders them
 * 0-based". The claim's *mechanism* is a phantom (the engine's projection is
 * 0-based and DSH's read leg now runs that very projection), but its *symptom*
 * is real and is caused by something else: the native engine already serializes
 * a notebook to nbformat JSON before handing the write request to the host
 * (`crates/pi-edit/src/files.rs:44-64` → `session.rs:256`), while DSH's writer
 * ran that JSON back through the notebook serializer
 * (`src/tools/hashline/native/writer.ts` → `serializeEditFileText`), which then
 * tried to parse JSON as cell-mapped text and threw.
 *
 * The decode is now the engine's own codec end to end: `read` calls
 * `readEditableNotebookText`, which delegates to `pi-natives`
 * `notebookToEditableText` — the same projection `crates/pi-edit/src/files.rs`
 * validates against. The corpus test below therefore pins the projection with
 * **literal expectations** instead of comparing against a second renderer
 * (which this change deleted).
 *
 * Every test here drives real code paths — the real `read` tool, the real
 * `executeHashlineSingle` entry point, the real native `EditSession` — against
 * real temp-dir `.ipynb` files. No engine mocks.
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import * as natives from "@oh-my-pi/pi-natives";
import { getDefault } from "../../src/tools/omp/config/settings-schema.ts";
import { Settings } from "../../src/tools/omp/config/settings.ts";
import type { ToolSession } from "../../src/tools/omp/sdk.ts";
import { readEditableNotebookText, serializeEditedNotebookText } from "../../src/tools/omp/edit/notebook.ts";
import {
	canonicalSnapshotKey,
	getFileSnapshotStore,
} from "../../src/tools/omp/edit/file-snapshot-store.ts";
import { executeHashlineSingle } from "../../src/tools/omp/edit/hashline/execute.ts";
import { buildHashlineEditPolicy } from "../../src/tools/hashline/native/policy.ts";
import { executeReadTool, renderReadOutput } from "../../src/tools/read/adapter/index.ts";
import { attachOmpSessionState, persistOmpSessionState } from "../../src/tools/shared/session-state.ts";
import type { RuntimeConfig } from "../../src/config/settings.ts";

/**
 * Realpath'd cwd, raw short-name session cwd: the engine compares `policy.cwd`
 * against its own canonical snapshot keys byte-wise, so `buildHashlineEditPolicy`
 * has to normalize it (see `native-edit-wiring.spec.ts`).
 */
const rawCwd = fs.mkdtempSync(path.join(os.tmpdir(), "t13-nb-"));
const cwd = fs.realpathSync.native(rawCwd);

/** Two cells (code + markdown) so the projection exercises the inter-cell join. */
const TWO_CELLS = {
	cells: [
		{ cell_type: "code", source: ["print(1)\n"], metadata: {}, execution_count: null, outputs: [] },
		{ cell_type: "markdown", source: ["# Title\n", "body\n"], metadata: {} },
	],
	metadata: {},
	nbformat: 4,
	nbformat_minor: 5,
};

/** The cell-mapped projection both renderers must agree on for {@link TWO_CELLS}. */
const TWO_CELLS_EDITABLE = "# %% [code] cell:0\nprint(1)\n\n# %% [markdown] cell:1\n# Title\nbody\n";

function config(): RuntimeConfig {
	return {
		editMode: "hashline",
		editFuzzyMatch: true,
		editFuzzyThreshold: 0.95,
		editEnforceSeenLines: false,
		editBlockAutoGenerated: true,
		readLineNumbers: false,
	} as unknown as RuntimeConfig;
}

/** A fresh DSH per-call `ToolSession`, exactly as the adapters build one. */
function makeSession(): ToolSession {
	return { cwd: rawCwd, settings: new Settings(config(), getDefault), hasEditTool: true } as unknown as ToolSession;
}

/** DSH's write channel, reduced to the file effect under test. */
const writes: string[] = [];
async function writethrough(dst: string, content: string): Promise<void> {
	writes.push(dst);
	await fs.promises.writeFile(dst, content, "utf8");
}

/** The DSH exec stub the read adapter reads `agent.session` from. */
function execFor(sessionKey: object): any {
	return { agent: { session: sessionKey }, signal: undefined };
}

function headerTag(text: string): string {
	const match = /^\[[^\]#]+#([0-9A-F]{4})\]/m.exec(text);
	if (!match) throw new Error(`no hashline header in ${JSON.stringify(text.slice(0, 200))}`);
	return match[1];
}

/** Run the real read tool and return the model-visible text plus its tag. */
async function readNotebook(
	file: string,
	sessionKey: object,
): Promise<{ rendered: string; tag: string }> {
	const out = await executeReadTool(execFor(sessionKey), config(), { path: file }, null as never);
	const rendered = renderReadOutput(out);
	return { rendered, tag: headerTag(rendered) };
}

/** A second per-call session re-attached to the same DSH session key. */
function reattached(sessionKey: object): ToolSession {
	const session = makeSession();
	attachOmpSessionState(session, sessionKey);
	return session;
}

function writeNotebook(name: string, doc: unknown, bom = false): string {
	const file = path.join(cwd, name);
	fs.writeFileSync(file, `${bom ? "\uFEFF" : ""}${JSON.stringify(doc, null, 1)}`, "utf8");
	return file;
}

/** Drive the native engine directly — the layer the DSH writer sits on. */
async function applyViaEngine(
	file: string,
	store: natives.EditStore,
	payload: string,
	onContent?: (content: string) => void,
): Promise<natives.EditApplyOutcome> {
	const session = new natives.EditSession(store, buildHashlineEditPolicy(makeSession()) as never, undefined);
	session.setArgsJson(JSON.stringify({ input: payload }));
	session.finish();
	try {
		return await session.apply({ lspFlush: false }, async (_error, request) => {
			const content = request.content ?? "";
			// Mirror the production writer's byte effect for all three ops so the
			// engine's own post-edit view is computed from what really landed.
			if (request.op === "delete") fs.rmSync(request.path, { force: true });
			else if (request.op === "move" && request.moveTo) {
				fs.writeFileSync(request.moveTo, content, "utf8");
				fs.rmSync(request.path, { force: true });
			} else fs.writeFileSync(request.path, content, "utf8");
			onContent?.(content);
			return { written: content };
		});
	} finally {
		session.close();
	}
}

afterAll(() => {
	fs.rmSync(rawCwd, { recursive: true, force: true });
});

describe("notebook (.ipynb) hashline round trip (T13)", () => {
	it("decodes the notebook corpus with literal expectations", async () => {
		// Literal expectations, not a comparison against a second renderer: the
		// read leg *is* the engine's decoder now (`readEditableNotebookText` →
		// `pi-natives`), which is what makes the tag `read` mints and the tag the
		// engine validates against structurally identical instead of merely
		// equal-by-inspection. These strings are the projection contract.
		const corpus: Array<[string, unknown, string]> = [
			["empty cells", { cells: [], metadata: {}, nbformat: 4, nbformat_minor: 5 }, ""],
			[
				"source as string",
				{ cells: [{ cell_type: "code", source: "x = 1\n" }], metadata: {}, nbformat: 4, nbformat_minor: 5 },
				"# %% [code] cell:0\nx = 1\n",
			],
			[
				"source as array",
				{ cells: [{ cell_type: "code", source: ["x = 1\n", "y = 2\n"] }], metadata: {}, nbformat: 4, nbformat_minor: 5 },
				"# %% [code] cell:0\nx = 1\ny = 2\n",
			],
			[
				"no trailing newline",
				{ cells: [{ cell_type: "code", source: ["x = 1"] }], metadata: {}, nbformat: 4, nbformat_minor: 5 },
				"# %% [code] cell:0\nx = 1",
			],
			[
				"empty cell",
				{ cells: [{ cell_type: "code", source: "" }], metadata: {}, nbformat: 4, nbformat_minor: 5 },
				"# %% [code] cell:0",
			],
			[
				"empty array cell",
				{ cells: [{ cell_type: "markdown", source: [] }], metadata: {}, nbformat: 4, nbformat_minor: 5 },
				"# %% [markdown] cell:0",
			],
			[
				"marker-like source line",
				{
					cells: [{ cell_type: "markdown", source: ["# %% [markdown] cell:3\n", "text\n"] }],
					metadata: {},
					nbformat: 4,
					nbformat_minor: 5,
				},
				"# %% [markdown] cell:0\n# %%% [markdown] cell:3\ntext\n",
			],
			[
				"cjk source",
				{
					cells: [{ cell_type: "code", source: ["# 中文注释\n", "print('你好')\n"] }],
					metadata: {},
					nbformat: 4,
					nbformat_minor: 5,
				},
				"# %% [code] cell:0\n# 中文注释\nprint('你好')\n",
			],
		];

		for (const [name, doc, expected] of corpus) {
			const file = writeNotebook("corpus.ipynb", doc);
			expect(await readEditableNotebookText(file, "corpus.ipynb"), `corpus: ${name}`).toBe(expected);
		}

		// The projection is 0-based — the phantom claim said DSH was 1-based
		// while the engine was 0-based.
		const file = writeNotebook("cells.ipynb", TWO_CELLS);
		const rendered = await readEditableNotebookText(file, "cells.ipynb");
		expect(rendered).toBe(TWO_CELLS_EDITABLE);
		expect(rendered).toContain("# %% [code] cell:0");
		expect(rendered).toContain("# %% [markdown] cell:1");
		expect(rendered).not.toContain("cell:1\nprint(1)");
	});

	it("keeps the legacy decode error text for every failure shape", async () => {
		// The decoder moved to the engine, so its failure text is now the
		// read tool's (and the patch/replace modes') user-facing text. These are
		// the exact strings the deleted TS decoder produced.
		const badJson = path.join(cwd, "badjson.ipynb");
		fs.writeFileSync(badJson, "{ not json", "utf8");
		await expect(readEditableNotebookText(badJson, "badjson.ipynb")).rejects.toThrow(
			"Invalid JSON in notebook: badjson.ipynb",
		);

		const noCells = path.join(cwd, "nocells.ipynb");
		fs.writeFileSync(noCells, JSON.stringify({ metadata: {} }), "utf8");
		await expect(readEditableNotebookText(noCells, "nocells.ipynb")).rejects.toThrow(
			"Invalid notebook structure (missing cells array): nocells.ipynb",
		);

		const notObject = path.join(cwd, "notobject.ipynb");
		fs.writeFileSync(notObject, "[]", "utf8");
		await expect(readEditableNotebookText(notObject, "notobject.ipynb")).rejects.toThrow(
			"Invalid notebook structure (expected object): notobject.ipynb",
		);

		const badCell = path.join(cwd, "badcell.ipynb");
		fs.writeFileSync(badCell, JSON.stringify({ cells: [{ cell_type: "other" }] }), "utf8");
		await expect(readEditableNotebookText(badCell, "badcell.ipynb")).rejects.toThrow(
			"Invalid notebook cell 0 in badcell.ipynb",
		);

		// ENOENT stays ours (`readNotebookDocument`'s old message).
		await expect(readEditableNotebookText(path.join(cwd, "absent.ipynb"), "absent.ipynb")).rejects.toThrow(
			"File not found: absent.ipynb",
		);
	});

	it("mints the read tag over the 0-based cell-mapped text, not the raw JSON", async () => {
		const file = writeNotebook("mint.ipynb", TWO_CELLS);
		const rawJson = fs.readFileSync(file, "utf8");
		const { rendered, tag } = await readNotebook(file, {});

		// Read output is cell-mapped and 0-based.
		expect(rendered).toContain("1:# %% [code] cell:0");
		expect(rendered).toContain("# %% [markdown] cell:1");
		expect(rendered).not.toContain("# %% [code] cell:1");

		// The tag is the whole-file hash of the projection, not of the JSON bytes.
		expect(tag).toBe(natives.hashlineFileHash(TWO_CELLS_EDITABLE));
		expect(tag).not.toBe(natives.hashlineFileHash(rawJson));
	});

	it("validates the read tag in the engine and applies the edit", async () => {
		const file = writeNotebook("engine.ipynb", TWO_CELLS);
		const sessionKey = {};
		const { tag } = await readNotebook(file, sessionKey);
		const store = getFileSnapshotStore(reattached(sessionKey));

		let handed: string | undefined;
		const outcome = await applyViaEngine(file, store, `[engine.ipynb#${tag}]\nPUT 2-2:\n+print(2)`, (c) => {
			handed = c;
		});

		expect(outcome.isError).toBe(false);
		expect(outcome.text).not.toContain("file changed between read and edit");

		// The engine hands the host already-serialized nbformat JSON — not the
		// cell-mapped projection. This is the fact DSH's writer gets wrong.
		expect(handed).toBeDefined();
		expect(handed!.startsWith("{")).toBe(true);
		const parsed = JSON.parse(handed!) as { cells: Array<{ source: string[] }> };
		expect(parsed.cells[0].source).toEqual(["print(2)\n"]);
		expect(parsed.cells[1].source).toEqual(["# Title\n", "body\n"]);

		// The model-facing text is still the cell-mapped projection of the new file.
		expect(outcome.text).toContain("2:print(2)");
		expect(outcome.files[0]?.newText?.startsWith("{")).toBe(true);
	});

	it("mints tags the engine accepts when cell source is malformed", async () => {
		// The whole point of running the engine's own decoder: `read`'s tag and the
		// engine's validation projection cannot disagree. A `source` array holding
		// non-string elements is exactly where the deleted TS renderer diverged —
		// it produced `"a5"` where the engine sees `"a"` — so a tag minted from
		// that projection was rejected with `hash #… is not from this session` and
		// the notebook was readable-but-not-editable. (Independent verification,
		// task-16: the engine-side projection wins and the old tags really did
		// fail; this case keeps that fixed.)
		const doc = { cells: [{ cell_type: "code", source: ["a", 5] }], metadata: {}, nbformat: 4, nbformat_minor: 5 };
		const file = writeNotebook("malformed.ipynb", doc);
		const engineProjection = natives.notebookToEditableText(fs.readFileSync(file, "utf8"), "malformed.ipynb");

		// Read leg == engine projection, and the tag is that projection's hash.
		expect(await readEditableNotebookText(file, "malformed.ipynb")).toBe(engineProjection);
		const sessionKey = {};
		const { tag } = await readNotebook(file, sessionKey);
		expect(tag).toBe(natives.hashlineFileHash(engineProjection));

		// …and the engine accepts it: the edit applies instead of being rejected.
		const store = getFileSnapshotStore(reattached(sessionKey));
		const outcome = await applyViaEngine(file, store, `[malformed.ipynb#${tag}]\nPUT 2-2:\n+print(9)`);
		expect(outcome.isError).toBe(false);
		expect(outcome.text).not.toContain("is not from this session");
		// Line 2 of the projection was `a` (no trailing newline), so the replaced
		// cell source keeps that shape.
		expect(JSON.parse(fs.readFileSync(file, "utf8")).cells[0].source).toEqual(["print(9)"]);
	});

	it("writes valid nbformat JSON and accepts a second edit with the fresh tag", async () => {
		const file = writeNotebook("roundtrip.ipynb", TWO_CELLS);
		const sessionKey = {};
		const store = getFileSnapshotStore(reattached(sessionKey));

		// Edit 1 — the engine's own JSON bytes land verbatim.
		const first = await readNotebook(file, sessionKey);
		expect((await applyViaEngine(file, store, `[roundtrip.ipynb#${first.tag}]\nPUT 2-2:\n+print(2)`)).isError).toBe(false);
		const afterFirst = fs.readFileSync(file, "utf8");
		expect(JSON.parse(afterFirst).cells[0].source).toEqual(["print(2)\n"]);

		// The engine re-renders the file it just wrote; a fresh read mints a tag
		// over that projection and the second edit must validate.
		const second = await readNotebook(file, sessionKey);
		expect(second.tag).not.toBe(first.tag);
		expect(second.rendered).toContain("2:print(2)");

		expect((await applyViaEngine(file, store, `[roundtrip.ipynb#${second.tag}]\nPUT 5-5:\n+# Retitled`)).isError).toBe(false);
		const afterSecond = fs.readFileSync(file, "utf8");
		const doc = JSON.parse(afterSecond) as {
			cells: Array<{ cell_type: string; source: string[] }>;
			nbformat: number;
			nbformat_minor: number;
		};
		expect(doc.cells[0].source).toEqual(["print(2)\n"]);
		expect(doc.cells[1].source).toEqual(["# Retitled\n", "body\n"]);
		expect(doc.nbformat).toBe(4);
		expect(doc.nbformat_minor).toBe(5);

		// A third read agrees with the bytes on disk (no drift between legs).
		const third = await readNotebook(file, sessionKey);
		expect(third.tag).toBe(natives.hashlineFileHash(natives.notebookToEditableText(afterSecond, "roundtrip.ipynb")));
	});

	it("round-trips a notebook through the real DSH entry point", async () => {
		const file = writeNotebook("real.ipynb", TWO_CELLS);
		const sessionKey = {};
		const { tag } = await readNotebook(file, sessionKey);
		const before = fs.readFileSync(file, "utf8");

		const result = await executeHashlineSingle({
			session: reattached(sessionKey),
			input: `[real.ipynb#${tag}]\nPUT 2-2:\n+print(2)`,
			writethrough,
		});

		expect(result.isError).toBeUndefined();
		const after = fs.readFileSync(file, "utf8");
		expect(after).not.toBe(before);
		expect(JSON.parse(after).cells[0].source).toEqual(["print(2)\n"]);
		expect(writes.at(-1)).toBe(file);

		// Second edit with the fresh tag from a new read.
		const second = await readNotebook(file, sessionKey);
		const result2 = await executeHashlineSingle({
			session: reattached(sessionKey),
			input: `[real.ipynb#${second.tag}]\nPUT 5-5:\n+# Retitled`,
			writethrough,
		});
		expect(result2.isError).toBeUndefined();
		expect(JSON.parse(fs.readFileSync(file, "utf8")).cells[1].source).toEqual(["# Retitled\n", "body\n"]);

		// The response's own header tag matches what a fresh read mints: the engine
		// renders its post-edit view from the bytes the host reported
		// (`EditWriteResponse.written`), so a mismatch would mean the two legs
		// diverged. The body is the changed region with context, not the whole
		// file, so compare row-by-row against the fresh read instead of as text.
		const text2 = result2.content.map(part => (part.type === "text" ? part.text : "")).join("");
		const third = await readNotebook(file, sessionKey);
		expect(headerTag(text2)).toBe(third.tag);

		const rowsOf = (text: string): Map<number, string> => {
			const rows = new Map<number, string>();
			for (const line of text.split("\n")) {
				const match = /^(\d+):(.*)$/.exec(line);
				if (match) rows.set(Number(match[1]), match[2]);
			}
			return rows;
		};
		const responseRows = rowsOf(text2);
		const readRows = rowsOf(third.rendered);
		expect(responseRows.size).toBeGreaterThan(0);
		for (const [lineNumber, content] of responseRows) {
			expect(readRows.get(lineNumber), `row ${lineNumber}`).toBe(content);
		}
	});

	it("moves a notebook through the real DSH entry point", async () => {
		const file = writeNotebook("mv-real.ipynb", TWO_CELLS);
		const dest = path.join(cwd, "mv-real-dest.ipynb");
		fs.rmSync(dest, { force: true });
		const sessionKey = {};
		const { tag } = await readNotebook(file, sessionKey);

		const result = await executeHashlineSingle({
			session: reattached(sessionKey),
			input: `[mv-real.ipynb#${tag}]\nMV mv-real-dest.ipynb`,
			writethrough,
		});

		expect(result.isError).toBeUndefined();
		expect(fs.existsSync(file)).toBe(false);
		const doc = JSON.parse(fs.readFileSync(dest, "utf8")) as { cells: unknown[] };
		expect(doc.cells).toHaveLength(2);

		// The moved notebook is editable under its new name.
		const moved = await readNotebook(dest, sessionKey);
		const second = await executeHashlineSingle({
			session: reattached(sessionKey),
			input: `[mv-real-dest.ipynb#${moved.tag}]\nPUT 2-2:\n+print(3)`,
			writethrough,
		});
		expect(second.isError).toBeUndefined();
		expect(JSON.parse(fs.readFileSync(dest, "utf8")).cells[0].source).toEqual(["print(3)\n"]);
	});

	it("refuses to create a notebook and directs to the write tool", async () => {
		// hashline is an edit-only mode: a missing section target is rejected
		// before the writer's `create` branch (covered in `native-writer.spec.ts`).
		const missing = path.join(cwd, "brand-new.ipynb");
		fs.rmSync(missing, { force: true });

		await expect(
			executeHashlineSingle({
				session: makeSession(),
				input: "[brand-new.ipynb#AB12]\nPUT <1:\n+print(1)",
				writethrough,
			}),
		).rejects.toThrow(/write tool/);
		expect(fs.existsSync(missing)).toBe(false);
	});

	it("hands the host notebook JSON for a move destination too", async () => {
		const file = writeNotebook("mv.ipynb", TWO_CELLS);
		const dest = path.join(cwd, "moved.ipynb");
		fs.rmSync(dest, { force: true });
		const sessionKey = {};
		const { tag } = await readNotebook(file, sessionKey);
		const store = getFileSnapshotStore(reattached(sessionKey));

		let handed: string | undefined;
		const outcome = await applyViaEngine(file, store, `[mv.ipynb#${tag}]\nMV moved.ipynb`, (c) => {
			handed = c;
		});

		expect(outcome.isError).toBe(false);
		expect(fs.existsSync(file)).toBe(false);
		// Same contract as `update`: the destination bytes are already nbformat JSON.
		expect(handed?.startsWith("{")).toBe(true);
		expect(JSON.parse(fs.readFileSync(dest, "utf8")).cells).toHaveLength(2);
	});

	it("reads a BOM-prefixed notebook the way the engine does", async () => {
		const file = writeNotebook("bom.ipynb", { cells: [{ cell_type: "code", source: ["print(1)\n"] }], metadata: {}, nbformat: 4, nbformat_minor: 5 }, true);
		const raw = fs.readFileSync(file, "utf8");
		expect(raw.startsWith("\uFEFF")).toBe(true);

		// The engine strips the BOM before parsing (`crates/pi-edit/src/notebook.rs`).
		expect(natives.notebookToEditableText(raw, "bom.ipynb")).toBe("# %% [code] cell:0\nprint(1)\n");

		// DSH's reader runs the engine's own decoder, so the read leg agrees with
		// the engine instead of throwing `Invalid JSON in notebook` on a file the
		// engine edits happily. (18.x alignment: v17.3.5's upstream TS had no BOM
		// handling either, so this was a pre-existing gap, not a migration bug.)
		expect(await readEditableNotebookText(file, "bom.ipynb")).toBe("# %% [code] cell:0\nprint(1)\n");

		// End to end: read → edit → valid JSON on disk, BOM consumed by the engine.
		const sessionKey = {};
		const { tag } = await readNotebook(file, sessionKey);
		const result = await executeHashlineSingle({
			session: reattached(sessionKey),
			input: `[bom.ipynb#${tag}]\nPUT 2-2:\n+print(2)`,
			writethrough,
		});
		expect(result.isError).toBeUndefined();
		const after = fs.readFileSync(file, "utf8");
		expect(after.startsWith("\uFEFF")).toBe(false);
		expect(JSON.parse(after).cells[0].source).toEqual(["print(2)\n"]);
	});

	it("still tolerates a BOM on the encode path (write / patch / replace)", async () => {
		// The decode half of this codec moved to the engine; the *encode* half
		// (`serializeEditedNotebookText`) is still ours and must still read a
		// BOM-prefixed file, because DSH's write/patch/replace paths run through
		// it. Delete this case when those modes move onto the Rust engine too.
		const file = writeNotebook(
			"bom-encode.ipynb",
			{ cells: [{ cell_type: "code", source: ["print(1)\n"], metadata: {}, execution_count: null, outputs: [] }], metadata: {}, nbformat: 4, nbformat_minor: 5 },
			true,
		);
		const serialized = await serializeEditedNotebookText(file, "bom-encode.ipynb", "# %% [code] cell:0\nprint(2)\n");
		expect(JSON.parse(serialized).cells[0].source).toEqual(["print(2)\n"]);
	});
});
