/**
 * T17-1 回归：write auto-generated 守卫（Windows 路径 basename 提取）。
 *
 * OMP 的 isAutoGeneratedFileName 用 `filePath.split('/').pop()` 取 basename，
 * Windows 反斜杠路径整串不匹配 `/^zz_generated\./`，守卫静默放行。本测试
 * 验证 `zz_generated.go`（已存在）被拒绝改写。
 */
import { afterEach, describe, expect, it } from 'vitest'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { executeWriteTool } from '../../src/tools/write/adapter/index.ts'

const tmpDirs: string[] = []
function tmpDir(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tool-plus-guard-'))
  tmpDirs.push(dir)
  return dir
}
afterEach(() => {
  for (const dir of tmpDirs.splice(0)) fs.rmSync(dir, { recursive: true, force: true })
})

function execFor(cwd: string): any {
  return { agent: { session: { header: { cwd } } }, signal: undefined }
}

describe('write auto-generated 守卫（T17-1）', () => {
  it('`zz_generated.go`（已存在）被拒绝改写', async () => {
    const dir = tmpDir()
    const file = path.join(dir, 'zz_generated.go')
    fs.writeFileSync(file, '// original\n')

    await expect(
      executeWriteTool(execFor(dir), {} as never, { path: file, content: '// x' }),
    ).rejects.toThrow(/auto-generated/i)
  })
})
