/**
 * `write` 在 hashline 模式下清理"read 回显"的内容，以及它给模型的提示是否属实。
 *
 * 本文件守护的是一处移植偏差（不是上游问题）。上游
 * `refs/oh-my-pi/packages/coding-agent/src/tools/write.ts:333-352` 的
 * `stripWriteContentWithPotentialLooseHeader` 两处都比**文本**：
 *
 *   const originalText = lines.join("\n");
 *   const cleanedText  = stripHashlinePrefixes(lines).join("\n");
 *   if (cleanedText !== originalText) { … }
 *
 * 我们这版曾写成 `if (cleaned !== lines)` —— 比的是**数组身份**，而
 * `stripHashlinePrefixes` 走 pi-natives，跨边界必然返回新数组，于是恒真：
 *
 *  - `stripped` 恒为 true，提示 "auto-stripped hashline display prefixes"
 *    在每次写盘时都出现，包括什么都没剥的纯文本写入（误导模型以为内容被改过）；
 *  - 提前 return 让后面那段"松散 header 兜底"变成死代码。原生剥离器只认规范的
 *    `[path#<4 hex>]` 头；畸形/legacy 头（`[h#1]`、`[a.ts#]`、6 位 tag、非 hex）
 *    它不认，靠这段兜底把 header 行摘掉后再剥编号前缀。上游会写成裸内容，
 *    我们这版会把 `[h#1]` 和 `1:` 原样写进文件。
 *
 * 用例走完整真实链路：`executeWriteTool` → `WriteTool` → 真实
 * `@oh-my-pi/pi-natives` 剥离器 → `writethroughNoop` 落盘 → 真实临时文件。
 * 判别依据是磁盘字节 + 提示文本，不看内部对象。
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { executeWriteTool } from "../../src/tools/write/adapter/index.ts";
import type { RuntimeConfig } from "../../src/config/settings.ts";

const rawCwd = fs.mkdtempSync(path.join(os.tmpdir(), "t18-write-strip-"));
const cwd = fs.realpathSync.native(rawCwd);

afterAll(() => {
	fs.rmSync(rawCwd, { recursive: true, force: true });
});

/** hashline 模式：只有 `hashLines` 为真时 write 才会尝试剥前缀。 */
function config(): RuntimeConfig {
	return {
		editMode: "hashline",
		editFuzzyMatch: true,
		editFuzzyThreshold: 0.95,
		editEnforceSeenLines: false,
		editBlockAutoGenerated: true,
		readLineNumbers: false,
	} as unknown as RuntimeConfig;
}

function execFor(): any {
	return { agent: { session: { header: { cwd } } }, signal: undefined };
}

const NOTE = "auto-stripped hashline display prefixes";

let seq = 0;
/** Write `content` to a fresh file in the temp cwd; return the bytes + tool text. */
async function writeFile(content: string): Promise<{ file: string; onDisk: string; text: string }> {
	seq += 1;
	const file = path.join(cwd, `strip-${seq}.txt`);
	const out = await executeWriteTool(execFor(), config(), { path: file, content });
	return { file, onDisk: fs.readFileSync(file, "utf8"), text: out.text };
}

describe("write hashline 前缀清理", () => {
	it("规范 4-hex 头 + 编号行：剥成裸内容，并如实提示", async () => {
		const { onDisk, text } = await writeFile(`[${path.join(cwd, "well.txt")}#1A2B]\n1:alpha\n2:beta\n`);
		expect(onDisk).toBe("alpha\nbeta\n");
		expect(text).toContain(NOTE);
	});

	it("畸形/legacy 头（原生剥离器不认）：兜底仍要剥成裸内容", async () => {
		const { onDisk, text } = await writeFile("[h#1]\n1:alpha\n2:beta\n");
		expect(onDisk).toBe("alpha\nbeta\n");
		expect(text).toContain(NOTE);
	});

	it("其余畸形头形状：空 tag / 6 位 tag / 非 hex tag", async () => {
		for (const head of ["[a.ts#]", "[a.ts#1A2B3C]", "[a.ts#zzzz]"]) {
			const { onDisk } = await writeFile(`${head}\n1:alpha\n`);
			expect(onDisk, `${head} 未被兜底清理`).toBe("alpha\n");
		}
	});

	it("没有任何可剥前缀：内容原样写入，且不得声称已剥离", async () => {
		const { onDisk, text } = await writeFile("plain\nlines\n");
		expect(onDisk).toBe("plain\nlines\n");
		expect(text).not.toContain(NOTE);
	});

	it("不是 hashline 头（缺 `#`）：原样写入，且不得声称已剥离", async () => {
		const content = "[a.ts]\n1:alpha\n";
		const { onDisk, text } = await writeFile(content);
		expect(onDisk).toBe(content);
		expect(text).not.toContain(NOTE);
	});

	it("混合内容（头 + 编号行 + 普通行）：一律不动，也不得声称已剥离", async () => {
		const content = `[${path.join(cwd, "mixed.txt")}#1A2B]\n1:alpha\nplain line\n`;
		const { onDisk, text } = await writeFile(content);
		expect(onDisk).toBe(content);
		expect(text).not.toContain(NOTE);
	});
});
